### ISSUE TITLE
[BUG] @ListenBreak未实现

### ISSUE THREAD

**Issue by liuc-c** [ForteScarlet/simpler-robot#10]
version: `2.0.0-ALPHA.7` 

module: ``

## 疑问描述

两个监听器，第一个监听器A用了PriorityConstant.FIRST标记第一个执行，第二个监听器B是用@OnPrivate，所以应该是默认的PriorityConstant.TENTH，最后一个执行，A监听器使用了@ListenBreak注解，想要实现A监听器执行成功后不执行B监听器，但是最后两个监听器都执行了。

**Comment by ForteScarlet** [comment]
正常情况下， 如果返回值是一个 `true` 或者一个非 `null` 的值，即视为**执行成功**，
相反的，如果返回 `false` 或者一个 `null` 则视为 **执行失败**，此注解将失效。

不过，这是正常情况下，我刚刚看了一下，@ListenBreak的相关功能没有被实现，因此这个功能暂时不能用。

预计下个版本修复这个问题，感谢反馈

**Comment by ForteScarlet** [comment]
[v2.0.0-ALPHA.9](https://github.com/ForteScarlet/simpler-robot/releases/tag/v2.0.0-ALPHA.9)

**Comment by plumekanade** [comment]
version: 2.0.5

**Comment by plumekanade** [comment]
version: 2.0.5
一个监听器是@OnGroup注解
另一个监听器注解有:
@OnGroup
@ListenBreak
@Filters(atBot = true)
@Priority(PriorityConstant.FIRST)
发现两个监听器都会输出日志，监听没有被中断，SpringBoot的项目

**Comment by ForteScarlet** [comment]
> version: 2.0.5
> 一个监听器是@ongroup注解
> 另一个监听器注解有:
> @ongroup
> @ListenBreak
> @filters(atBot = true)
> @priority(PriorityConstant.FIRST)
> 发现两个监听器都会输出日志，监听没有被中断，SpringBoot的项目

上面的回复我已经提到了，如果标注了`@ListenBreak`，那么当监听函数的返回值是 `true` 或者一个任意的 **非null** 返回值才会被阻断。
