### ISSUE TITLE
[QU.]获取bot实例

### ISSUE THREAD

**Issue by plumekanade** [ForteScarlet/simpler-robot#104]
version: `2.0.7`

module: ``

## 疑问描述
怎么去获取已经注册登录的bot实例....
基于SpringBoot运行的

**Comment by ForteScarlet** [comment]
注入一个 `BotManager` 实例。
```java
@Autowried
private BotManager manager;
```
参考文档：[BOT管理](https://www.yuque.com/simpler-robot/simpler-robot-doc/bfc97c)
