### ISSUE TITLE
[SUG]希望可以提供一个监听类的拦截器

### ISSUE THREAD

**Issue by kukume** [ForteScarlet/simpler-robot#111]
希望可以提供一个监听类的拦截器，这个拦截器可以写在这个类里面，根据条件来是否拦截，最好能在这个拦截器里面往后面需要执行的监听方法提供一些实例变量，提供的实例变量可以直接在监听方法的参数进行注入

**Comment by ForteScarlet** [comment]
#114  #115

**Comment by ForteScarlet** [comment]
抢鲜体验 [v2.1.0-BETA.1](https://github.com/ForteScarlet/simpler-robot/releases/tag/v2.1.0-BETA.1)
