### ISSUE TITLE
[BUG] 监听新人入群事件获取OperatorInfo报NPE

### ISSUE THREAD

**Issue by LYF-Uaena** [ForteScarlet/simpler-robot#13]
version: 2.0.0-ALPHA.10

module: `` 

## 问题描述
监听新人入群事件时，从GroupMemberIncrease中获取OperatorInfo报NPE异常

## 相关日志
相关代码
@OnGroupMemberIncrease
public void groupMemberIncreaseListener(GroupMemberIncrease increaseMsg, MsgSender sender) {
        log.info("新增了一名群成员");
        long operatorCode = Objects.requireNonNull(increaseMsg.getOperatorInfo()).getOperatorCodeNumber();

## 复现方式
监听新人入群事件

**Comment by ForteScarlet** [comment]
使用mirai组件的时候，mirai（v1.3.2）尚无法获取 **操作者（operator）** 的信息，因此获取的操作者为null。[参考①](https://github.com/ForteScarlet/simpler-robot/blob/91befa18ba957006a5c54ab5b2ddd7d296713a14/component-parent/component-mirai/src/main/java/love/forte/simbot/component/mirai/message/event/MiraiMemberChanged.kt#L41)


且核心中，也规定**操作者信息**可能会因为不同组件的特性而允许其可能为null，使用的时候应当注意进行判断。[参考②](https://github.com/ForteScarlet/simpler-robot/blob/91befa18ba957006a5c54ab5b2ddd7d296713a14/core-parent/api/src/main/java/love/forte/simbot/api/message/containers/OperatingContainers.kt#L197)  [参考③](https://www.yuque.com/simpler-robot/simpler-robot-doc/yuopk0#CidFQ)
