### ISSUE TITLE
[QU.]我该如何切换登录协议 以及收不到部分人私聊信息

### ISSUE THREAD

**Issue by mashiro-hjl** [ForteScarlet/simpler-robot#140]
version: `2.1.0-BETA.1` 

module: ``

## 疑问描述

请问我该如何切换登录协议，我在文档看过了，没找到怎么切换登录协议，以及收不到部分人的私聊信息该如何解决 谢谢

**Comment by ForteScarlet** [comment]
切换协议的文档内容在mirai组件下的配置章节里：https://www.yuque.com/simpler-robot/simpler-robot-doc/lnx5nh

**Comment by ForteScarlet** [comment]
收不到部分人的私聊消息有可能是发消息的人被主动屏蔽，如果是其他原因请先排查自己的账号设置以及代码逻辑可能出现的相关问题，目前还暂时没有人反馈过会出现部分人私聊收不到的情况，mirai那边也没有类似问题

**Comment by ForteScarlet** [comment]
以及，`2.1.x` 下已经有releases版本，不建议继续使用`-BETA`的版本

**Comment by mashiro-hjl** [comment]
> 以及，`2.1.x` 下已经有releases版本，不建议继续使用`-BETA`的版本

感谢你的回复 目前所有问题均已解决 谢谢
