### ISSUE TITLE
[SUG]希望可以提供机器人对话

### ISSUE THREAD

**Issue by kukume** [ForteScarlet/simpler-robot#142]
## 建议描述
比如：
```
我：绑定手机号
机器人：请输入手机号码
我：12345678
机器人：绑定成功
```
机器人对话。例如提供注解@Filter("绑定手机号")，手动调用发送消息发送请输入手机号码，然后在该方法内调用一个方法，可暂时挂起该线程，将等待该用户的下一句话，在该用户发送消息后，可以调用一个方法获取该消息，并完成逻辑操作

**Comment by ForteScarlet** [comment]
此功能可以在 `v2.2.0` 支持 `kotlin suspend function (可挂起函数)` 之后自行实现（通过自定义挂起），你可以使用 [v2.2.0-DEV.9](https://github.com/ForteScarlet/simpler-robot/releases/tag/v2.2.0-DEV.9) 来抢先体验对可挂起函数的支持。

**Comment by kukume** [comment]
不用Kotlin可以实现吗？有文档吗？

**Comment by ForteScarlet** [comment]
不依靠可挂起函数就需要通过自行设置状态来实现“伪”等待，或者自己通过实现一种“回调”机制来实现。
这会很麻烦，未来版本或许会追加对Java更友好的实现方式，但是这需要时间与考虑。

目前阶段，你可以用以下思路实现：
1. 通过一个主要的监听函数来监听一个对话的发起，比如 `绑定手机号` 
2. 某个人发起对话后，记录这个人与对应的状态，并在另一个监听函数中对发送者和状态进行判断，如果这个人处于“绑定手机号”的状态，则对他的消息进行处理

实际上最好的方式还是依靠kotlin的挂起函数实现，因为这不会导致线程阻塞，也会有更优雅的代码

至于通用的实现方式，会列入新功能的思考范围内。

**Comment by kukume** [comment]
Kotlin使用新特性的文档有木有

**Comment by ForteScarlet** [comment]
直接定义挂起函数即可。
```kotlin
@OnGroup
suspend fun listen(msg: GroupMsg) = suspendCoroutine {
    // suspend function block
}
```

**Comment by ForteScarlet** [comment]
参考 [常见场景 - 实现BOT对话模式](https://www.yuque.com/simpler-robot/simpler-robot-doc/ycycgy)

**Comment by LYF-Uaena** [comment]
java是不是可以考虑使用redis的key失效监听来判断会话超时？

**Comment by kukume** [comment]
谢谢大佬。我看看
