### ISSUE TITLE
[SUG]希望可以增强动态变量提取

### ISSUE THREAD

**Issue by kukume** [ForteScarlet/simpler-robot#146]
## 建议描述
目前动态变量提取只能提取文本，希望在target为msg的时候，可以提取图片、at等信息。
例如  @Filter(value = "搜图{{image}}")
发送：搜图+图片，可以把一个图片对象通过参数注入的方式获取到该图片对象。
发送  搜图+at某人，可以从参数获取到该at的qq

**Comment by ForteScarlet** [comment]
动态变量提取本身就是基于正则group实现的，目的就是为了提取字符串
有关于这种提取其他参数的方式，未来或许会考虑使用其他方式来支持这种对消息类型的截取，但会基于Filter而不是target

**Comment by ForteScarlet** [comment]
顺便一提，mirai下使用频繁使用msg会有一定程度的性能问题，更建议使用messageContent

**Comment by ForteScarlet** [comment]
https://github.com/ForteScarlet/simpler-robot/blob/469549ba82e260f8a4a5cec6ce9dc0f60f9cfbd6/simbot-boots/simboot-api/src/main/kotlin/love/forte/simboot/listener/FunctionalBindableEventListener.kt#L154-L174
