### ISSUE TITLE
[QU.]拿cookie

### ISSUE THREAD

**Issue by kukume** [ForteScarlet/simpler-robot#151]
version: `最新版` 

module: ``

## 疑问描述

getter.getAuthInfo().getAuths().toMap();  方法拿到的map，这些东西怎么解密？
![image](https://user-images.githubusercontent.com/45278810/127776825-1a8e61a5-2067-47d2-b033-eb2b8a2c34f1.png)

**Comment by ForteScarlet** [comment]
那些数字就是byte，它们就是byte数组。原本直接转为字符串的方式会导致一部分数据出现乱码，因此使用了这种方式。
你可以 `split(",")` 然后将他们转为 `byte[]` 后再转为字符串

**Comment by ForteScarlet** [comment]
不过要注意，不是所有的数据都是`byte[]`, 比如`creationTime`的值就是一个时间戳
