### ISSUE TITLE
[QU.]可以实现监听minecraft服务端吗?

### ISSUE THREAD

**Issue by XinSin-top** [ForteScarlet/simpler-robot#152]
version: `` 

module: ``

## 疑问描述

如何实现监听minecraft的BungeeCord和fabric服务端呢？
能实现在群聊向bungeeCord和fabric发送指令吗？

**Comment by ForteScarlet** [comment]
理论上肯定可以，你只要能够找到允许获取、发送指令的服务端mod或者插件，然后整合这个mc插件和mirai组件就行了。
至于有哪些mod或者插件能用，这个我并没有了解过，也许你需要自己去mcbbs探索探索。

**Comment by XinSin-top** [comment]
ok 谢谢大佬我去看看相关的文档
