### ISSUE TITLE
[QU.]使用过程中好像接收不了图片和文件，只有id，请问如何获取qq发送过来的文件流

### ISSUE THREAD

**Issue by daline21** [ForteScarlet/simpler-robot#153]
version: `` 

module: ``

**Comment by ForteScarlet** [comment]
图片是有`url`属性的，文件目前确实无法获取url，只能得到id、名称、大小等基础属性。

**Comment by daline21** [comment]
那后续是否可以加上url，最近正在开发一些文件图片库管理功能，需要用到url这个属性，发现无法获取图片和文件

**Comment by daline21** [comment]
另外我想基于redis开发一个会话功能，只需要java, 还是同时需要使用java 和 kotlin 语言

**Comment by daline21** [comment]
目前只会java

**Comment by ForteScarlet** [comment]
mirai不存在的属性是加不上的

**Comment by ForteScarlet** [comment]
> 另外我想基于redis开发一个会话功能，只需要java, 还是同时需要使用java 和 kotlin 语言

只要想实现用什么语言都能实现

**Comment by daline21** [comment]
哦哦好的，谢谢大佬！
