### ISSUE TITLE
[BUG] 突然发现无法发送图片-2021.9.10

### ISSUE THREAD

**Issue by xi-yue-233** [ForteScarlet/simpler-robot#159]
不知道是什么原因，昨天晚上开始突然无法发送图片，换账号试也是这样的问题，也没有报错信息，就是发不出来，在服务器和本地主机上都有这个问题。除了图片，语音消息却可以发送。
![N1_HFH_)7WGZKZ9`5P$QVNY](https://user-images.githubusercontent.com/58218656/132741532-9883135b-01f5-42f3-96b3-039b9600c787.png)

**Comment by ForteScarlet** [comment]
这是 mirai 出现的突发性问题，参考 [mirai #1536](https://github.com/mamoe/mirai/issues/1536) , 并请追踪官方的反馈处理进度。
目前其给出的反馈中的解决办法：

> 尝试 [2.7.1-dev-1](https://github.com/mamoe/mirai/releases/tag/v2.7.1-dev-1), 如一周内无任何错误反馈则默认此问题已解决

在simbot中，即尝试手动导入 [2.7.1-dev-1](https://github.com/mamoe/mirai/releases/tag/v2.7.1-dev-1) 版本的mirai来尝试修复。
