### ISSUE TITLE
[QU.] 这段代码会出现无法发送图片的情况吗

### ISSUE THREAD

**Issue by liuzheng2000** [ForteScarlet/simpler-robot#164]
![图片](https://user-images.githubusercontent.com/52021646/133918974-59e9ab50-e5b2-47dd-80f2-fe2e53a9dbcb.png)
大佬这段代码会出现无法发送图片的情况吗？

**Comment by ForteScarlet** [comment]
你试试不就得了

**Comment by ForteScarlet** [comment]
如果出现无法发送图片的问题，参考：
- <https://www.yuque.com/simpler-robot/simpler-robot-doc/ie2t71>
- #159
