### ISSUE TITLE
[QU.]

### ISSUE THREAD

**Issue by liuzheng2000** [ForteScarlet/simpler-robot#165]
![图片](https://user-images.githubusercontent.com/52021646/133997425-eafffe02-0292-42d6-8ae4-dc9ecdd2800d.png)
simbot-mirai-spring-boot-demo
2.2.1版本为什么会找不到包那？

**Comment by ForteScarlet** [comment]
参考 <https://www.yuque.com/simpler-robot/simpler-robot-doc/rvsl9p>
