### ISSUE TITLE
滑块登陆（device.json）

### ISSUE THREAD

**Issue by dnslin** [ForteScarlet/simpler-robot#167]
## 疑问描述

首次登陆 出现滑块认证 
按照readerme 用了Mirai for 安卓 拿到了 device.json
但是文档里面似乎并没有怎么使用这个 device.json

**Comment by ForteScarlet** [comment]
mirai组件下可以通过配置 `simbot.component.mirai.deviceInfoFile` 指定 `device.json` 
参考文档 <https://www.yuque.com/simpler-robot/simpler-robot-doc/lnx5nh>

**Comment by dnslin** [comment]
抱歉了 没有仔细阅读 叨扰了(笑哭
