### ISSUE TITLE
[QU.]持续会话作用域的会话归属问题

### ISSUE THREAD

**Issue by dnslin** [ForteScarlet/simpler-robot#178]
version: `` 
2.3.0-BETA.1

module: ``

## 疑问描述
持续会话作用域
```java
inal ContinuousSessionScopeContext sessionContext = (ContinuousSessionScopeContext) context.getContext(ListenerContext.Scope.CONTINUOUS_SESSION);
```
依照上面的代码能够得到一个sessionContext也就是持续会话作用域
但是按照demo所说 

/*
     注意！你应当考虑一个问题：同一个人同时触发多次同样的会话， 比如它同时发了两次'start'.
     这个问题的解决应当由你自行解决，比如创建会话之前，先去检查是否已经存在。
 */

就像是这样 我不理解的是有什么凭借去判断当前会话属于哪个用户开启的 
或者说同一个用户发起两次同样的会话该怎么去判断
我看了 sessionContext 里的方法 似乎没有这种“凭借”
请开发者指点迷津！！ 谢谢

**Comment by ForteScarlet** [comment]
demo中提到的开启一个会话的 `key`, 是 `group + ':' + code`, 也就是一个群中某个人对应的唯一key。因此最简单的，在开启一个会话之前，判断这个 key 的会话是否存在就可以得知是否已经存在对应的会话了。

其他的，也可以通过map或者其他方法缓存你创建过的会话来进行判断。

**Comment by dnslin** [comment]
这个key我是知道的但是我疑惑的是改用key怎么去判断这个对应的会话
难道用一个hashmap 将key做键 ContinuousSessionScopeContext sessionContext这个对象作为值
每次有一个触发 就在map里面去新增？ 同时 ContinuousSessionScopeContext sessionContext也要新增一次吗？

**Comment by ForteScarlet** [comment]
map记录key确实可以，但是直接用 `get(String group, String key)` ，得到null即代表不存在此会话，通过这个判断即可。

假如你创建的会话已经存在，则如果再其尚未结束时创建同一个key的会话，则旧会话会被立即cancel。

**Comment by dnslin** [comment]
多谢！！！！
