### ISSUE TITLE
怎么配置掉线重连[QU.]

### ISSUE THREAD

**Issue by ilxyil** [ForteScarlet/simpler-robot#180]
## 疑问描述

使用了springboot的demo，但是偶尔会出现心跳超时然后账号掉线的情况，这种情况下怎么能设计自动重连？

**Comment by ForteScarlet** [comment]
实际上mirai自身带掉线重连，如果经常出现掉线的问题，我推荐的解决方法是：
- 更新版本到较新的版本
- 通过定时任务周期性的向自己的某个群发送心跳消息，比如“我还在线，时间：xxxx”
- 参考文档 <https://www.yuque.com/simpler-robot/simpler-robot-doc/lnx5nh> 来自定义mirai的配置。除了通过配置文件，下面还有直接操作mirai配置类的方案。我印象中其中是有跟心跳、重连相关的内容的。
