### ISSUE TITLE
[QU.]群消息监听优先级

### ISSUE THREAD

**Issue by ilxyil** [ForteScarlet/simpler-robot#189]
同时设置两个群消息监听，其中一个全量监听，另一个添加filter过滤，发送一条消息会触发两个监听，这个能不能设置如果触发了一个监听的话，另一个监听就不启动。

**Comment by ForteScarlet** [comment]
参考：
- [监听阻断](https://www.yuque.com/simpler-robot/simpler-robot-doc/qmpgzt#7xQGN)
- [监听优先级](https://www.yuque.com/simpler-robot/simpler-robot-doc/qmpgzt#9ajHi)
