### ISSUE TITLE
mirai组件不支持嵌套合并转发

### ISSUE THREAD

**Issue by Water-HuXH** [ForteScarlet/simpler-robot#216]
转发合并的聊天记录里面，再套一个聊天记录。复读后，第二个嵌套的聊天记录不显示

**Comment by ForteScarlet** [comment]
**如果是使用的 `2.3.7` 或以下版本：**
嵌套的合并转发是是 mirai v2.9.0-M1 ([mirai#1198](https://github.com/mamoe/mirai/issues/1198)) 才支持的功能，但是 simbot v2.3.7目前内部所依赖的mirai版本为 `v2.8.2`. 你可以尝试修改mirai版本：
```xml
<properties>
    <mirai.version>2.9.2</mirai.version>
</properties>
```

或者直接手动导入更高版本的mirai依赖，或者等simbot2跟进mirai版本。

**如果使用的是 simbot3 版本：**
simbot3目前最新的mirai组件是2.9.2版本的，请提供相关代码和依赖。

**Comment by ForteScarlet** [comment]
v2, v3 版本最新版本mirai内置版本均提升至2.9.0以上，理论上此问题已被解决。
