### ISSUE TITLE
有办法将base64的图片发送给用户吗

### ISSUE THREAD

**Issue by vudsen** [ForteScarlet/simpler-robot#226]
### 疑问描述

这边是模拟某个网站登录，需要过验证码，后台拿到验证码图片后再以base64的形式发送给用户，有办法实现吗。。。

**Comment by ForteScarlet** [comment]
你可以将base64字符串转为字节流/字节数组进行发送。

**Comment by vudsen** [comment]
我想的是直接在聊天里发base64格式的图片，，

**Comment by ForteScarlet** [comment]
图片无论如何最终都需要作为流进行上传。因此如果你需要通过聊天发送base64字符串，你就需要通过bot获取后进行解析。

**Comment by vudsen** [comment]
Sender里面没有发送流的方法，难道是拿到图片后保存到本地然后再用猫猫码发图片发过去吗

**Comment by ForteScarlet** [comment]
你可以参考：
- 2.x: <https://www.yuque.com/simpler-robot/simpler-robot-doc/hcf9gq#6uDuc>
- 3.x: <https://www.yuque.com/simpler-robot/simpler-robot-doc/zi293k#HDrcL>

**Comment by vudsen** [comment]
找到了，感谢
