### ISSUE TITLE
3.0版本java我获取到OriginBotManager后，没法正常获取到里面bot，然后进行直接发消息操作

### ISSUE THREAD

**Issue by jaiser** [ForteScarlet/simpler-robot#236]
### 问题描述

3.0版本java我获取到OriginBotManager后，没法正常获取到里面bot，然后进行直接发消息操作
我想提供web接口给外部调用能够通过qq通知，但是没法获取到bot，就没法发送了

### 版本号

v3.0.0

**Comment by ForteScarlet** [comment]
3.0中，`OriginBotManager` 的作用是获取所有的 `BotManager` 而不是 Bot。你需要先获取BotManager，再通过对应的BotManager获取bot。
参考：
- <https://www.yuque.com/simpler-robot/simpler-robot-doc/rqtil8>
- <https://simbot.forte.love/docs/next/defition/bot-manager/>

**Comment by jaiser** [comment]
您好，我是许家军，您的邮件我已收到，我将尽快查看，谢谢。

**Comment by jaiser** [comment]
好的，收到，测试可以使用了，谢谢
