### ISSUE TITLE
如何在mirai组件中监听头像戳一戳事件

### ISSUE THREAD

**Issue by 412221574** [ForteScarlet/simpler-robot#237]
### 疑问描述

可以监听bot被人戳一戳的消息嘛

**Comment by ForteScarlet** [comment]
2.x中戳一戳是 `nudge` 类型的CAT码，能够在私聊或者群聊事件的消息列表中得到。可以参考 <https://www.yuque.com/simpler-robot/simpler-robot-doc/qn8q4q#ccjjW>

3.x中的戳一戳，`MiraiNudge` 是**仅**用于发送的戳一戳对象，`MiraiNudgeEvent` 是戳一戳的事件。
**但是** `MiraiNudgeEvent` 还没有实现，因此尚不可用。你暂时可以通过 [UnsupportedMiraiEvent](https://www.yuque.com/simpler-robot/simpler-robot-doc/wx97i9#Bwae1) ，并判断 `if(originalEvent instanceof NudgeEvent)` 来得到mirai原生的戳一戳事件。

**Comment by 412221574** [comment]
2.x 发送戳一戳是可以的.. 我尝试了使用自定义监听器监听机器人本身被戳一戳 的消息是监听不到的

**Comment by 412221574** [comment]
哦哦哦... 忘了补充了 是群聊....

**Comment by ForteScarlet** [comment]
2.x中，你可以尝试在监听群消息的时候，获取message列表，判断其中是否存在 `nudge` 类型的CatCode，如果存在，判断 `from` 属性是否等于 bot 的 id。

**Comment by ForteScarlet** [comment]
超时关闭
