### ISSUE TITLE
可以指定机器人的登录方式吗？

### ISSUE THREAD

**Issue by 412221574** [ForteScarlet/simpler-robot#245]
### 疑问描述

版本 ： 2.X

**Comment by 412221574** [comment]
使用了 2.x 的spring boot 集成了 springboot-starter   发现登录方式是平板,我想改成手机登录. 查了下语雀的文档 发现没有相关的配置... 想问一下有其他方法可以实现吗？

**Comment by ForteScarlet** [comment]
但是2.x的mirai组件很久之前默认的协议就变成手机了，建议适当升级版本。

**Comment by ForteScarlet** [comment]
mirai组件的相关配置参考 <https://www.yuque.com/simpler-robot/simpler-robot-doc/lnx5nh>

但是2.x的mirai组件很久之前默认的协议就变成手机了，建议适当升级版本。

**Comment by 412221574** [comment]
好的感谢 找到了...
