### ISSUE TITLE
Q: 依赖包导入错误

### ISSUE THREAD

**Issue by cxjzl** [ForteScarlet/simpler-robot#262]
### 问题描述

有些依赖拉不下来

import love.forte.simbot.annotation.OnGroupAddRequest;
import love.forte.simbot.annotation.OnGroupMemberIncrease;
import love.forte.simbot.api.message.MessageContent;
import love.forte.simbot.api.message.MessageContentBuilder;
import love.forte.simbot.api.message.MessageContentBuilderFactory;
import love.forte.simbot.api.message.containers.AccountInfo;
import love.forte.simbot.api.message.containers.BotInfo;
import love.forte.simbot.api.message.containers.GroupInfo;
import love.forte.simbot.api.message.events.GroupAddRequest;
import love.forte.simbot.api.message.events.GroupMemberIncrease;
import love.forte.simbot.api.sender.Sender;
import love.forte.simbot.api.sender.Setter;

### 版本号

2.3.4

**Comment by ForteScarlet** [comment]
参考 <https://www.yuque.com/simpler-robot/simpler-robot-doc/rvsl9p>
