### ISSUE TITLE
将simbot引入Maven聚合项目时，无法读取Bot配置文件

### ISSUE THREAD

**Issue by yjrguxing** [ForteScarlet/simpler-robot#271]
猜测此时读取的配置路径为RuoYi-Vue-master/src/main/rescources
![图片](https://user-images.githubusercontent.com/38355410/166857787-907097cb-417a-4b9c-b2e3-98ffe28b724f.png)

**Comment by ForteScarlet** [comment]
在你的程序环境中增加相对应的 `kotlinx-serialization` 解析库依赖。以JSON格式的配置文件为例，增加：
```xml
<dependency>
    <groupId>org.jetbrains.kotlinx</groupId>
    <artifactId>kotlinx-serialization-json</artifactId>
    <version>1.3.2</version>
</dependency>
```
后再做尝试。

相关参考：[kotlinx-serialization](https://github.com/Kotlin/kotlinx.serialization)
