### ISSUE TITLE
Q: 实体无法序列化

### ISSUE THREAD

**Issue by coWhy** [ForteScarlet/simpler-robot#277]
### 建议描述

org.springframework.data.redis.serializer.SerializationException: Could not write JSON: (was java.lang.NullPointerException) (through reference chain: love.forte.simbot.component.mirai.message.MiraiMemberAccountInfo["member"]->net.mamoe.mirai.internal.contact.NormalMemberImpl["bot"]->net.mamoe.mirai.internal.QQAndroidBot["configuration"]->net.mamoe.mirai.utils.BotConfiguration["loginSolver"]->net.mamoe.mirai.utils.StandardCharImageLoginSolver["input"]->net.mamoe.mirai.utils.StandardCharImageLoginSolver$input$1["context"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: love.forte.simbot.component.mirai.message.MiraiMemberAccountInfo["member"]->net.mamoe.mirai.internal.contact.NormalMemberImpl["bot"]->net.mamoe.mirai.internal.QQAndroidBot["configuration"]->net.mamoe.mirai.utils.BotConfiguration["loginSolver"]->net.mamoe.mirai.utils.StandardCharImageLoginSolver["input"]->net.mamoe.mirai.utils.StandardCharImageLoginSolver$input$1["context"])    at org.springframework.data.redis.serializer.Jackson2JsonRedisSerializer.serialize(Jackson2JsonRedisSerializer.java:88)SUG:

**Comment by ForteScarlet** [comment]
绝大多数实体都不是为了序列化而存在。其内部可能存在很多东西，通常不能直接进行序列化。如果有需要请考虑自建模型类等与之对应的类型并进行转化。
