### ISSUE TITLE
v3.0.0无法获取到机器人信息

### ISSUE THREAD

**Issue by michik0** [ForteScarlet/simpler-robot#283]
### 问题描述

使用的Spring Boot版本为2.6.6，Java8
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/72622336/169250563-70e2ca7e-4dd8-42c1-a797-81003dc82860.png">

### 版本号

v3.0.0

**Comment by ForteScarlet** [comment]
请提供具体的版本号，以及debug日志（ 至少包括 `love.forte.simbot` 和 `love.forte.simboot` 下的debug日志 ）
