### ISSUE TITLE
Q: 当项目中存在多个@Listener的时候 会存在一条消息被多个监听到 从而执行多个方法

### ISSUE THREAD

**Issue by minamishino** [ForteScarlet/simpler-robot#288]
### 问题描述

如何解决标题中描述的问题

### 版本号

3.0.0.preview.8.1

**Comment by ForteScarlet** [comment]
监听函数可以返回 `EventResult` 类型来进行流程控制。例如返回 `EventResult.truncate()` 代表阻止后续其他监听的执行。

**Comment by minamishino** [comment]
> 监听函数可以返回 类型来进行流程控制。例如返回 代表阻止后续其他监听的执行。`EventResult``EventResult.truncate()`

我想问一下，关于Listener注解有没有拦截器这种东西 可以对消息未被监听器处理之前预处理消息

**Comment by ForteScarlet** [comment]
> 我想问一下，关于Listener注解有没有拦截器这种东西 可以对消息未被监听器处理之前预处理消息

有。但如有其他问题需求请在新的issue中提问。

**Comment by ForliyScarlet** [comment]
此issue已经在‘等待反馈’状态下5日未应答。如果在‘陈旧’状态下逾期2日将会被视为无效过期并关闭。

**Comment by ForliyScarlet** [comment]
此issue已经在「陈旧」状态下逾期2日未应答, 视为无效过期并关闭。
