### ISSUE TITLE
重连失败

### ISSUE THREAD

**Issue by fhh-coder** [ForteScarlet/simpler-robot#296]
### 问题描述

程序运行一段时间后，会提示 Connection lost, reconnecting... (NettyChannelException(message=null, cause=null))，重连失败的异常。

### 版本号

v2.3.4

**Comment by ForteScarlet** [comment]
请使用v2最新版本并提供包含错误的完整debug日志。

**Comment by ForliyScarlet** [comment]
此issue已经在‘等待反馈’状态下5日未应答。如果在‘陈旧’状态下逾期2日将会被视为无效过期并关闭。

**Comment by ForliyScarlet** [comment]
此issue已经在「陈旧」状态下逾期2日未应答, 视为无效过期并关闭。
