### ISSUE TITLE
我该如何从OnGroupMsgRecall 消息撤回的事件获取到撤回的消息缓存，已经开启了mirai的消息缓存

### ISSUE THREAD

**Issue by mashiro-hjl** [ForteScarlet/simpler-robot#318]
### 版本号

2.3.4

### 疑问描述

请问我如何从消息缓存中拿到已经被撤回的消息，在撤回的事件中我只获取到了一些id以及撤回的时间，我想通过撤回的事件监听中从消息缓存拿到被撤回的消息。谢谢。

**Comment by mashiro-hjl** [comment]
我已经看了很多次文档了，但是可能是因为我技术有限，因为我还在学习中，并没有找到相对应的文档，等候您的解答。

**Comment by ForteScarlet** [comment]
在mirai组件中，参考 <https://www.yuque.com/simpler-robot/simpler-robot-doc/ho2gv9> 。

**Comment by ForteScarlet** [comment]
如果已经开启了缓存，请在日志中确认是否生效（debug日志有所体现），且需要注意缓存仅能缓存bot启动后接收到的消息。如果上述尝试均为生效，请提供相关逻辑代码、配置文件和debug日志。

**Comment by mashiro-hjl** [comment]
> 如果已经触发了缓存，请注意是否生效（在调试日志中确认之后有相关代码），并且需要注意仅快速启动机器人启动接收的消息。文件和调试日志。

非常感谢你的回答，很遗憾，我目前的技术并没有弄明白，我已经通过将聊天记录存储到数据库来实现防撤回了。
