### ISSUE TITLE
关于自定义过滤器的使用问题

### ISSUE THREAD

**Issue by wuyou-123** [ForteScarlet/simpler-robot#356]
### 版本号

v3.0.0.preview.17.0

### 疑问描述

![image](https://user-images.githubusercontent.com/69062567/175949088-d5995bf3-d8e4-44d3-abca-d8d1c05a77a7.png)
![image](https://user-images.githubusercontent.com/69062567/175949241-3c9623c4-e69c-4a52-9bed-05b5a20020eb.png)
额是要这么写吗

**Comment by ForteScarlet** [comment]
大概意思差不多。
```kotlin
GameEventFilter::class.createInstance() // Why?
```
但是通过反射去创建实例是多此一举的。

**Comment by wuyou-123** [comment]
![image](https://user-images.githubusercontent.com/69062567/176066316-b3d7117c-f5b8-4063-a2aa-b7bcc6c4a07b.png)
好了
