### ISSUE TITLE
这里多了一个打印

### ISSUE THREAD

**Issue by wuyou-123** [ForteScarlet/simpler-robot#358]
### 建议描述

![image](https://user-images.githubusercontent.com/69062567/175972839-2c150bcf-8541-40a7-b153-c05e603cf166.png)
![image](https://user-images.githubusercontent.com/69062567/175972922-a107cbb7-74fc-4e05-a5cf-13e7e4fb6698.png)

**Comment by ForteScarlet** [comment]
追踪 https://github.com/simple-robot/simbot-component-mirai/issues/43
