### ISSUE TITLE
当前版本有没有手动注册监听器的实现方式

### ISSUE THREAD

**Issue by wuyou-123** [ForteScarlet/simpler-robot#361]
### 版本号

v3.0.0.preview.17.1

### 疑问描述

我想通过自定义注解实现手动注册监听器,用来实现管理所有监听器的功能

**Comment by ForteScarlet** [comment]
向依赖中注入 `EventListener` 实例即可注册自定义监听函数。参考 `@Listener` 文档注释或 [API Doc](https://simple-robot-library.github.io/simbot3-main-apiDoc/v3.0.0.preview.17.1/simbot-boots/simboot-core-annotation/love.forte.simboot.annotation/-listener/index.html)

不提供 _运行时动态注册_ 监听函数的内容。
