### ISSUE TITLE
[QUE] @Filter(s)的复数使用方式、类级别监听注释、消息事件发送者信息

### ISSUE THREAD

**Issue by HeilantG** [ForteScarlet/simpler-robot#37]
## 建议描述

1. 在2.0中   @Filter 注解的 value 属性为何不能为多个
2. 希望可以继续维持1.x中 @OnPrivate 与 @OnGroup 可以直接对一个类生效的特性,
3. 现在我该如何在mirai组件中获取消息的发送者qq(曾经的 msg.getQQCode() 方法)

**Comment by ForteScarlet** [comment]
参考文档：[@Filters](https://www.yuque.com/simpler-robot/simpler-robot-doc/qlm4du#iswLk)
当你需要多个@filter的时候，java中，你可以：
1: 
```java
@Filter( ... )
@Filter( ... )
public void listen(){ ... }
```

2: 
```java
@Filters(
   value = {
     @Filter( ... ), @FIlter( ... )
   }
)
public void listen2(){ ... }
```

kotlin中，只能使用方法2.

**Comment by ForteScarlet** [comment]
2 中的类级别注释已经在[2.0.0-BETA.7](https://github.com/ForteScarlet/simpler-robot/releases/tag/v2.0.0-BETA.7)中实现了

**Comment by ForteScarlet** [comment]
3，关于发送者的消息，在`accountInfo` 中。具体参考 [信息容器](https://www.yuque.com/simpler-robot/simpler-robot-doc/yuopk0) 和 [事件类型](https://www.yuque.com/simpler-robot/simpler-robot-doc/ct1u6l)。

**Comment by ForteScarlet** [comment]
咋样，如果没啥问题直接close就行了👌
