### ISSUE TITLE
[BUG] @Filter未匹配正则表达式

### ISSUE THREAD

**Issue by HeilantG** [ForteScarlet/simpler-robot#38]
version: `` 2.0.0-BETA.6

module: `` core

## 问题描述

@Filter 对于其中正则表达式解析似乎不太对

## 复现方式

`  @OnPrivate
  @Filter(value = ".*A.*")
  public void A(PrivateMsg msg, MsgSender sender) {
    System.out.println("A->A");
  }`

方法如上 此监听的正则表达式好像没有生效,仅当我输入`.*A.*`时,监听才会触发
注:@OnGroup中匹配似乎是正常的

**Comment by ForteScarlet** [comment]
2.x中，`@Filter` 的默认匹配方式为 `MatchType.EQUALS`, 即 `equals` 匹配，参考 [@Filter](https://www.yuque.com/simpler-robot/simpler-robot-doc/qlm4du#IBQYn) 中的 matchType参数

**Comment by ForteScarlet** [comment]
#37 
如果测试了没啥问题就直接自己close就可以了，还有问题的话再说👻
