### ISSUE TITLE
加入dependencyManagement报错NoClassDefFoundError: kotlin/Result（报错已解决）

### ISSUE THREAD

**Issue by ZeyuanGuo** [ForteScarlet/simpler-robot#389]
### 版本号

V2.4.0

### 疑问描述

简单使用了一段时间bot后去学了Spring boot，之后想做定时任务，按照Spring boot的方式添加依赖的版本管理，加入了
![image](https://user-images.githubusercontent.com/92578848/180018251-0ceb1d21-cd3a-4d5a-845a-ce8278acbfee.png)
![image](https://user-images.githubusercontent.com/92578848/180021849-af80797e-a424-47bc-9b2a-633f05f84e58.png)
（报错的时候下面两个没加version，用management管理）
启动报错
![image](https://user-images.githubusercontent.com/92578848/180020303-4acc2991-3bd0-4ac1-98a9-417d654a5fca.png)
从这个报错没找到他有问题的jar包在哪；之后删去management，将加入的依赖逐个声明版本就可以正常运行了
个人理解是不是因为这个management干扰了下面simbot相关的依赖版本；如果是的话修改它指定的version或者范围能否解决
或者只能逐个指定版本？
另外控制台打印的日志在这一过程之后没有颜色了，Spring boot用的spring.output.ansi.enabled=always也没起作用（？）
打扰大佬了

**Comment by ForteScarlet** [comment]
Spring中会提供kotlin的版本控制。以Spring Boot 2.7.1 为例可参考 [spring-boot/dependency-versions](https://docs.spring.io/spring-boot/docs/current/reference/html/dependency-versions.html#appendix.dependency-versions)

simbot 2.4.0使用的1.6.21版本的kotlin，而2.0.6的Spring Boot版本太过陈旧，kotlin版本会被低版本所覆盖。

请考虑使用更高版本的Spring Boot或者根据Spring Boot官方文档的描述覆盖kotlin的版本控制。

日志问题请检查日志依赖冲突，理论上这与simbot无关。

**Comment by ZeyuanGuo** [comment]
了解了，感谢讲解
只知道他是版本控制，对他控制了什么没有理解在瞎想
日志问题我后面试了一下，是因为在引入Spring boot那几个依赖之后和bot的日志冲突，所以我除去了bot的日志，就导致没有颜色识别
大佬强强，谢谢大佬
