### ISSUE TITLE
定时器依赖项无法解析

### ISSUE THREAD

**Issue by M1911-A1** [ForteScarlet/simpler-robot#394]
### 版本号

v2.0

### 问题描述

Could not find artifact love.forte.simple-robot.time-task:time-task-core:pom:unknown in central (https://repo.maven.apache.org/maven2)
Could not find artifact love.forte.simple-robot.time-task:time-task-core:pom:unknown in central (https://repo.maven.apache.org/maven2)

### 复现方式

下载依赖项即可

**Comment by ForteScarlet** [comment]
1. 请提供你所配置的具体坐标和版本号。
2. 在Spring Boot项目环境下，如非必要，请直接使用Spring Boot自带的定时任务功能。可参考：
   - [integration.html#scheduling](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#scheduling)
   - [integration.html#scheduling-annotation-support-scheduled](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#scheduling-annotation-support-scheduled)

**Comment by ForteScarlet** [comment]
并且 simbot2 的 `time-task-*` 下相关模块已许久未维护，如非必要并不建议使用。

**Comment by M1911-A1** [comment]
好的，那我去用Sprin Boot的定时任务功能去了。感谢你的解答
