### ISSUE TITLE
在3.0.0.preview.20.0版本中 部署在服务器上无法使用sendBlocking方法发送消息

### ISSUE THREAD

**Issue by BronyaSe** [ForteScarlet/simpler-robot#395]
### 版本号

3.0.0.preview.20.0

### 问题描述

在服务器上面部署后，通过debug发现在执行sendBlocking方法时无法发送消息，没有任何错误输出
在自己的电脑上是可以使用此方法发送消息的
服务器在阿里云和腾讯云都测试过

### 复现方式

部署在服务器上

**Comment by ForteScarlet** [comment]
参考 <https://www.yuque.com/simpler-robot/simpler-robot-doc/ie2t71> ，这个问题与 v2 的原因是一致的。

**Comment by BronyaSe** [comment]
测试过私聊了 还是无法发送

**Comment by ForteScarlet** [comment]
尝试：
1. 在本地环境使用私聊/群聊
2. 使用其他账号测试这些逻辑

如果上述情况中出现可以发送的情况，则依然属于前述的风控情况，只是比较严重；如果全部都不行，则继续反馈；

**Comment by ForteScarlet** [comment]
> 在自己的电脑上是可以使用此方法发送消息的

刚刚没有看到这一句，如果在本地可以的话，那大概就是异地登录的风控。这是程度比较重的风控，或许可以尝试：
- 删除项目目录下的 `cache` 目录
- 多挂一段时间
- 增加账号活跃度等操作。

目前没有一个能十分有效的解决办法。

其他相关参考：
- https://github.com/mamoe/mirai/issues/1925
- https://mirai.mamoe.net/topic/763/%E7%BE%A4%E6%B6%88%E6%81%AF%E4%B8%8D%E6%98%BE%E7%A4%BA-%E5%88%A0%E9%99%A4cache%E6%96%87%E4%BB%B6%E5%A4%B9%E5%90%8E%E9%87%8D%E6%96%B0%E5%90%AF%E5%8A%A8%E5%8F%88%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%98%BE%E7%A4%BA/7

**Comment by BronyaSe** [comment]
好的，谢谢大佬解答
