### ISSUE TITLE
GroupMemberRemarkChanged 群成员备注变动

### ISSUE THREAD

**Issue by LYF-Uaena** [ForteScarlet/simpler-robot#396]
### 版本号

3.0.0-beta-M3

### 疑问描述

在2.X的版本中有GroupMemberRemarkChanged 群成员备注变动这个监听，但M3的版本中没有找到类似这个的event，请大佬help一哈

**Comment by ForteScarlet** [comment]
参考：https://simple-robot-library.github.io/simbot3-component-mirai-apiDoc/v3.0.0.0-beta-M1/simbot-component-mirai-core/love.forte.simbot.component.mirai.event/-mirai-member-card-change-event/index.html

**Comment by LYF-Uaena** [comment]
可以了，禁言或其他changeevent可以正常捕获，这个备注变动应该是mirai的主动行为，需要被改的人说话才可触发，感谢大佬
