### ISSUE TITLE
使用Simple 2.4.0，并参考您的b站视频进行操作，但始终出现看不明白的报错

### ISSUE THREAD

**Issue by wRuaLi** [ForteScarlet/simpler-robot#405]
### 版本号

v2.4.0

### 疑问描述

参考您的b站视频为“[simple]v如何用Java写qq机器人 V2.1.0 贴心女友级教程”
https://www.bilibili.com/video/BV1Y54y1G7T8?spm_id_from=333.1007.top_right_bar_window_history.content.click

如下：
"C:\Program Files\Java\jdk-17.0.3.1\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2022.2\lib\idea_rt.jar=62053:C:\Program Files\JetBrains\IntelliJ IDEA 2022.2\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\Administrator\Desktop\simbot-mirai-demo-testbot\target\classes;C:\Users\Administrator\.m2\repository\love\forte\simple-robot\component-mirai\2.4.0\component-mirai-2.4.0.jar;C:\Users\Administrator\.m2\repository\love\forte\simple-robot\http\client-core\2.4.0\client-core-2.4.0.jar;C:\Users\Administrator\.m2\repository\love\forte\simple-robot\http\client-ktor\2.4.0\client-ktor-2.4.0.jar;C:\Users\Administrator\.m2\repository\love\forte\simple-robot\serialization\json-core\2.4.0\json-core-2.4.0.jar;C:\Users\Administrator\.m2\repository\love\forte\simple-robot\serialization\json-fastjson\2.4.0\json-fastjson-2.4.0.jar;C:\Users\Administrator\.m2\repository\com\alibaba\fastjson\1.2.83\fastjson-1.2.83.jar;C:\Users\Administrator\.m2\repository\io\ktor\ktor-client-core-jvm\1.6.8\ktor-client-core-jvm-1.6.8.jar;C:\Users\Administrator\.m2\repository\io\ktor\ktor-http-jvm\1.6.8\ktor-http-jvm-1.6.8.jar;C:\Users\Administrator\.m2\repository\io\ktor\ktor-utils-jvm\1.6.8\ktor-utils-jvm-1.6.8.jar;C:\Users\Administrator\.m2\repository\io\ktor\ktor-io-jvm\1.6.8\ktor-io-jvm-1.6.8.jar;C:\Users\Administrator\.m2\repository\io\ktor\ktor-http-cio-jvm\1.6.8\ktor-http-cio-jvm-1.6.8.jar;C:\Users\Administrator\.m2\repository\io\ktor\ktor-network-jvm\1.6.8\ktor-network-jvm-1.6.8.jar;C:\Users\Administrator\.m2\repository\io\ktor\ktor-client-okhttp\1.6.8\ktor-client-okhttp-1.6.8.jar;C:\Users\Administrator\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib\1.6.10\kotlin-stdlib-1.6.10.jar;C:\Users\Administrator\.m2\repository\org\jetbrains\annotations\13.0\annotations-13.0.jar;C:\Users\Administrator\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk7\1.6.10\kotlin-stdlib-jdk7-1.6.10.jar;C:\Users\Administrator\.m2\repository\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;C:\Users\Administrator\.m2\repository\com\squareup\okhttp3\okhttp\4.9.3\okhttp-4.9.3.jar;C:\Users\Administrator\.m2\repository\com\squareup\okio\okio\2.8.0\okio-2.8.0.jar;C:\Users\Administrator\.m2\repository\cn\hutool\hutool-crypto\5.7.19\hutool-crypto-5.7.19.jar;C:\Users\Administrator\.m2\repository\cn\hutool\hutool-core\5.7.19\hutool-core-5.7.19.jar;C:\Users\Administrator\.m2\repository\net\mamoe\mirai-core-api-jvm\2.11.1\mirai-core-api-jvm-2.11.1.jar;C:\Users\Administrator\.m2\repository\org\jetbrains\kotlinx\kotlinx-coroutines-jdk8\1.6.1\kotlinx-coroutines-jdk8-1.6.1.jar;C:\Users\Administrator\.m2\repository\net\mamoe\mirai-console-compiler-annotations-jvm\2.11.1\mirai-console-compiler-annotations-jvm-2.11.1.jar;C:\Users\Administrator\.m2\repository\org\jetbrains\kotlinx\kotlinx-serialization-core-jvm\1.3.2\kotlinx-serialization-core-jvm-1.3.2.jar;C:\Users\Administrator\.m2\repository\org\jetbrains\kotlinx\kotlinx-serialization-json-jvm\1.3.2\kotlinx-serialization-json-jvm-1.3.2.jar;C:\Users\Administrator\.m2\repository\me\him188\kotlin-jvm-blocking-bridge-runtime-jvm\2.0.0-162.1\kotlin-jvm-blocking-bridge-runtime-jvm-2.0.0-162.1.jar;C:\Users\Administrator\.m2\repository\net\mamoe\mirai-core-utils-jvm\2.11.1\mirai-core-utils-jvm-2.11.1.jar;C:\Users\Administrator\.m2\repository\org\jetbrains\kotlinx\kotlinx-serialization-protobuf-jvm\1.3.2\kotlinx-serialization-protobuf-jvm-1.3.2.jar;C:\Users\Administrator\.m2\repository\org\jetbrains\kotlinx\atomicfu-jvm\0.17.2\atomicfu-jvm-0.17.2.jar;C:\Users\Administrator\.m2\repository\io\netty\netty-all\4.1.63.Final\netty-all-4.1.63.Final.jar;C:\Users\Administrator\.m2\repository\org\apache\logging\log4j\log4j-api\2.17.2\log4j-api-2.17.2.jar;C:\Users\Administrator\.m2\repository\org\bouncycastle\bcprov-jdk15on\1.64\bcprov-jdk15on-1.64.jar;C:\Users\Administrator\.m2\repository\org\jetbrains\kotlinx\kotlinx-io-jvm\0.1.16\kotlinx-io-jvm-0.1.16.jar;C:\Users\Administrator\.m2\repository\org\jetbrains\kotlinx\kotlinx-io\0.1.16\kotlinx-io-0.1.16.jar;C:\Users\Administrator\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk8\1.6.21\kotlin-stdlib-jdk8-1.6.21.jar;C:\Users\Administrator\.m2\repository\org\jetbrains\kotlinx\kotlinx-coroutines-core\1.6.3\kotlinx-coroutines-core-1.6.3.jar;C:\Users\Administrator\.m2\repository\org\jetbrains\kotlinx\kotlinx-coroutines-core-jvm\1.6.3\kotlinx-coroutines-core-jvm-1.6.3.jar;C:\Users\Administrator\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-common\1.6.21\kotlin-stdlib-common-1.6.21.jar;C:\Users\Administrator\.m2\repository\love\forte\simple-robot\core\2.4.0\core-2.4.0.jar;C:\Users\Administrator\.m2\repository\love\forte\simple-robot\api\2.4.0\api-2.4.0.jar;C:\Users\Administrator\.m2\repository\love\forte\catcode\1.0.0-BETA.1\catcode-1.0.0-BETA.1.jar;C:\Users\Administrator\.m2\repository\love\forte\common\utils\1.0.7\utils-1.0.7.jar;C:\Users\Administrator\.m2\repository\love\forte\common\ioc\1.0.7\ioc-1.0.7.jar;C:\Users\Administrator\.m2\repository\love\forte\common\configuration\1.0.7\configuration-1.0.7.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-yaml\2.12.5\jackson-dataformat-yaml-2.12.5.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.12.5\jackson-databind-2.12.5.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.12.5\jackson-annotations-2.12.5.jar;C:\Users\Administrator\.m2\repository\org\yaml\snakeyaml\1.27\snakeyaml-1.27.jar;C:\Users\Administrator\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.12.5\jackson-core-2.12.5.jar;C:\Users\Administrator\.m2\repository\love\forte\common\log\1.0.7\log-1.0.7.jar;C:\Users\Administrator\.m2\repository\love\forte\common\language\1.0.7\language-1.0.7.jar;C:\Users\Administrator\.m2\repository\org\jetbrains\kotlin\kotlin-reflect\1.6.21\kotlin-reflect-1.6.21.jar love.simbot.example.SimbotExampleApplication
.------..------..------..------..------..------.
|S.--. ||I.--. ||M.--. ||B.--. ||O.--. ||T.--. |
| :/\: || (\/) || (\/) || :(): || :/\: || :/\: |
| :\/: || :\/: || :\/: || ()() || :\/: || (__) |
| '--'@|| '--'F|| '--'O|| '--'R|| '--'T|| '--'E|
`------'`------'`------'`------'`------'`------'
                                          v2.4.0

Tips: 你知道吗？simbot开发团队中离职次数最多的人与个头最高的人是同一个人。

[2022-07-31T03:33:27.374892100]-[INFO ] | love.simbot.example.SimbotExampleApplication : Active resources: [simbot.yml]
[2022-07-31T03:33:29.397895300]-[INFO ] |  love.f.s.c.m.c.MiraiEventCacheConfiguration : Disable default mirai message cache.
2022-07-31 03:33:29 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2022-07-31 03:33:29 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
[2022-07-31T03:33:29.816897100]-[ERROR] |              love.f.s.c.m.c.MiraiBotVerifier : Verifier bot(1009219413) failed.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at love.forte.common.ioc.MethodDependPass.invoke(DependPass.kt:76)
	at love.forte.common.ioc.DependCenter.init(DependCenter.kt:108)
	at love.forte.simbot.core.SimbotApp.initDependCenter(SimbotApp.kt:434)
	at love.forte.simbot.core.SimbotApp.run$core(SimbotApp.kt:279)
	at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt:509)
	at love.forte.simbot.core.SimbotApp$Run.run$default(SimbotApp.kt:472)
	at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt)
	at love.forte.simbot.core.SimbotApp.run(SimbotApp.kt)
	at love.simbot.example.SimbotExampleApplication.main(SimbotExampleApplication.java:33)
Caused by: java.lang.IllegalStateException: Can't overwrite cause with a null
	at java.base/java.lang.Throwable.initCause(Throwable.java:463)
	at love.forte.simbot.component.mirai.configuration.MiraiBotVerifier.verity(MiraiBotVerifier.kt:115)
	at love.forte.simbot.component.mirai.configuration.MiraiBotManager.registerBot(MiraiBotManager.kt:103)
	at love.forte.simbot.core.configuration.CoreBotRegistrar.registerBots(CoreBotRegistrar.kt:65)
	... 13 more
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.internal.MiraiImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:362)
	at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:354)
	at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:42)
	at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:115)
	at love.forte.simbot.component.mirai.configuration.MiraiBotVerifier.verity(MiraiBotVerifier.kt:79)
	... 15 more

进程已结束,退出代码1

**Comment by ForteScarlet** [comment]
请提供项目所使用的版本信息，例如 `pom.xml` 或者 `build.gradle` 文件内容。

**Comment by wRuaLi** [comment]
pom.xml内容如下：
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>simbot.example</groupId>
    <artifactId>simbot-mirai-demo</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <simbot.version>2.4.0</simbot.version>
    </properties>

    <dependencies>
        
        <dependency>
            <groupId>love.forte.simple-robot</groupId>
            <artifactId>component-mirai</artifactId>
            <version>${simbot.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.5.3</version>
                <configuration>
                    
                    <mainClass>love.simbot.example.TestSimbotExampleApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>

**Comment by wRuaLi** [comment]
pom.xml内容如下：
```
<?xml` version="1.0" `encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>simbot.example</groupId>
    <artifactId>simbot-mirai-demo</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <simbot.version>2.4.0</simbot.version>
    </properties>

    <dependencies>
        <!-- 使用 mirai 组件。 -->
        <dependency>
            <groupId>love.forte.simple-robot</groupId>
            <artifactId>component-mirai</artifactId>
            <version>${simbot.version}</version><!--vv-->
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Springboot打包插件。使用 mvn package 进行打包。 -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.5.3</version>
                <configuration>
                    <!-- main方法所在类。 -->
                    <mainClass>love.simbot.example.TestSimbotExampleApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```

**Comment by ForteScarlet** [comment]
本地测试未复现，请尝试：
- 检查依赖是否正常被下载
- 清理本地仓库的 `*.lastUpdated` 文件
- 调整maven仓库镜像

等方式，然后再做尝试。

**Comment by ForliyScarlet** [comment]
此issue已经在「等待反馈」状态下5日未应答。如果在「陈旧」状态下逾期2日将会被视为无效过期并关闭。

**Comment by ForliyScarlet** [comment]
此issue已经在「陈旧」状态下逾期2日未应答, 视为无效过期并关闭。
