### ISSUE TITLE
验证时无限要求验证

### ISSUE THREAD

**Issue by ConstantineQAQ** [ForteScarlet/simpler-robot#414]
### 版本号

simbot-mirai-demo

### 问题描述

验证时无限要求验证

### 复现方式

通过ticket之后出现问题：不是常用设备，需要扫码登录，但是扫过一次后又出来了，无限次扫码

**Comment by ForteScarlet** [comment]
参考：
- https://github.com/mamoe/mirai/issues/2157
- https://github.com/mamoe/mirai/issues/2092

**Comment by ForliyScarlet** [comment]
此issue已经在「等待反馈」状态下5日未应答。如果在「陈旧」状态下逾期2日将会被视为无效过期并关闭。

**Comment by ForliyScarlet** [comment]
此issue已经在「陈旧」状态下逾期2日未应答, 视为无效过期并关闭。
