### ISSUE TITLE
自定义过滤器MostMatchType失效

### ISSUE THREAD

**Issue by wuyou-123** [ForteScarlet/simpler-robot#42]
version: `2.0.0-BETA.7` 

module: `filter` 

## 问题描述

监听器上加两个自定义过滤器,后面指定匹配规则失效
测试了两个方法,分别指定了mostMatchType = MostMatchType.ALL和mostMatchType = MostMatchType.ANY
都只执行了第一个过滤器,第一个过滤器返回true的情况下不会执行第二个过滤器,直接执行监听事件,第一个返回false才会执行第二个过滤器

**Comment by ForteScarlet** [comment]
`@Filters( mostMatchType = ... )` 参数是针对于 `@Filters` 的 `value` 参数，即（多个）子注解 `@Filter` 而使用的，针对于多个自定义过滤器，请使用 `@Filters( customMostMatchType = ... )`
