### ISSUE TITLE
当前登录存在安全风险，请使用常用设备或通过手机号登录

### ISSUE THREAD

**Issue by 791549729** [ForteScarlet/simpler-robot#423]
### 版本号

2.x

### 疑问描述

登录在使用TxCaptchaHelper通过验证后，显示 当前登录存在安全风险 ，不是网络环境异常

net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(QQ账号), code=237, title=安全提醒, message=当前登录存在安全风险，请使用常用设备或通过手机号登录。, errorInfo=)

**Comment by ForteScarlet** [comment]
参考：
- https://github.com/mamoe/mirai/issues/2117
- https://www.yuque.com/simpler-robot/simpler-robot-doc/ul3m12

**Comment by 791549729** [comment]
文档上面的方法都试了，目前没有用。
只能等几天试试看了
