### ISSUE TITLE
考虑出个纯控制台版本

### ISSUE THREAD

**Issue by Enderman-Teleporting** [ForteScarlet/simpler-robot#425]
### 建议描述

由于GUI(登录验证)对如面板那样的服务器不太友好,能否考虑基于2.4版本将登录验证由GUI专为控制台输出输入
![屏幕截图 2022-08-13 084718](https://user-images.githubusercontent.com/100068319/184461106-4403fbc0-cadd-4fa0-b404-67ecf2fda511.png)
?

**Comment by ForteScarlet** [comment]
GUI面板是由 `mirai-core` 所提供的。当在本地完成验证或者提供有效 `device.json` 的时候，在服务器上基本不会出现需要使用GUI面板的情况。
并且理论上，`mirai-core` 会检测当前环境，在不支持GUI的情况下会选择使用其他的控制台输出方式。

对于配置 `device.json` ，可以参考：

- https://www.yuque.com/simpler-robot/simpler-robot-doc/lnx5nh#jlb7w
- https://github.com/mamoe/mirai/issues?q=is%3Aissue+device.json

如果在极少数情况下需要自定义验证处理器，可以参考：

- https://github.com/mamoe/mirai/issues/347#issuecomment-633357882
- https://www.yuque.com/simpler-robot/simpler-robot-doc/lnx5nh#jlb7w

**Comment by Enderman-Teleporting** [comment]
好的,谢谢作者
