### ISSUE TITLE
如何发送匿名群消息

### ISSUE THREAD

**Issue by 791549729** [ForteScarlet/simpler-robot#428]
### 版本号

2.x

### 疑问描述

如何发送匿名群消息

**Comment by ForteScarlet** [comment]
未寻得 Mirai 中与 **发送匿名消息** 有关的API，Mirai 貌似不支持此API。如有需要，请向 [Mirai](https://github.com/mamoe/mirai) 官方 [提出issue](https://github.com/mamoe/mirai/issues/new/choose) 来寻求答案或申请特性。

如果 Mirai 实际上支持发送匿名消息或者通过了他们的特性申请，请提供相关资料或链接并重新打开此 issue。
