### ISSUE TITLE
该账户有设备锁/不常用登录地点/不常用登录设备的问题  一直提示需要验证

### ISSUE THREAD

**Issue by 791549729** [ForteScarlet/simpler-robot#438]
### 版本号

2.x

### 疑问描述

前两天好好的，改了一下protocol 登录设备为IPAD，就一直提示设备锁，需要扫码；我正常扫码之后关闭窗口，继续弹出提示需要验证。
我尝试把protocol修改回来、关闭设备锁、正常流程扫码试了很多次，都一直这样

**Comment by ForteScarlet** [comment]
Duplicate of #414

额外参考：<https://github.com/mamoe/mirai/issues?q=is%3Aissue+%E6%89%AB%E7%A0%81>

其他尝试：清理项目根目录下产生的 `.cache` 文件夹、重新配置 `device.json` 文件等。

**Comment by 791549729** [comment]
我使用了mirai框架直接进行登录，是可以的登录上去的。然后用simpler-robot还是一样无限需要扫码
我猜测是mirai不读取 device.json 的情况下  每次登录都是随机的设备，每次都需要进行滑动验证，之后再扫码能够登录成功
这边simpler-robot在没有 device.json 文件，清楚 .cache 文件夹之后登录不会再次需要进行滑动验证，只是需要扫码验证，这时候QQ风控或者情况就会导致需要一直需要扫码。
我建议修改一下，在没有 device.json 文件的情况下每次都随机设备，然后默认导出 device.json 文件

以上为个人根据自身情况的猜测， 仅供参考

**Comment by ForteScarlet** [comment]
如果希望导出 `device.json` 文件，可以增加配置 `simbot.component.mirai.deviceInfoOutput=true` （参考 
 https://www.yuque.com/simpler-robot/simpler-robot-doc/lnx5nh ）

如果希望调整为mirai的随机规则，可参考 https://www.yuque.com/simpler-robot/simpler-robot-doc/lnx5nh#jlb7w 进行配置。

simbot内本质上也是随机的，大致随机逻辑与mirai的类似，只不过替换了部分设备信息，可参考 :
https://github.com/ForteScarlet/simpler-robot/blob/dee633dc7e4cbb4c70524ba9e7d8c4b4aa7f081e/component/component-mirai/src/main/java/love/forte/simbot/component/mirai/configuration/MiraiConfiguration.kt#L232-L262

区别在于 `simbotMiraiDeviceInfo(c, s)` 中的随机种子默认情况下是固定为 `1` 的，但可以由配置项 `simbot.component.mirai.deviceInfoSeed=123456` 调整。（参考 
 https://www.yuque.com/simpler-robot/simpler-robot-doc/lnx5nh ）


对于 “无限扫码” 的情况我没遇见过，不清楚具体流程，下述内容可做简单尝试：
- 开启设备锁
- 登录扫码（或者其他需要用到手机账号）时，扫码结束后，手机账号退出登录/退出QQ，再进行下一步客户端验证操作
