### ISSUE TITLE
2.0的情况下，我想用机器人转发别人发的（本地文件，非链接）文件，

### ISSUE THREAD

**Issue by 930893138** [ForteScarlet/simpler-robot#450]
### 版本号

2.3.0

### 疑问描述

可是一直报错（ No 'file' or 'path' in [CAT:file,id=.......） ,请问这个问题怎么解决？

**Comment by ForteScarlet** [comment]
`file` 类型的猫猫码代表为 **群文件** 而不是发送的那种文件。如果仅希望直接转发一个消息，考虑使用：
```java
@OnGroup
public void onMsg(GroupMsg msg, Sender sender) {
    // 直接转发消息
    sender.sendGroupMsg("群号", msg.getMsgContent());
}
```

**Comment by 930893138** [comment]
我期望达到的效果的是，能把file类型的群文件，发送到自己指定的地址的位置，而不是消息。所以msg.getMsgContent()时发送过去的是


MiraiMessageChainContent(originalMessage=[mirai:source:[766],[246908683]][mirai:file:《单片机原理与应用》年.doc,/468b3d4a-3019-11ed-bbe2-5254002fac13,250368,102])


类似这样的数据，我想让他按照文件的形式发过去。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ForteScarlet/simpler-robot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月10日(星期六) 凌晨0:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ForteScarlet/simpler-robot] 2.0的情况下，我想用机器人转发别人发的（本地文件，非链接）文件， (Issue #450)





 
file 类型的猫猫码代表为 群文件 而不是发送的那种文件。如果仅希望直接转发一个消息，考虑使用：
 @OnGroup public void onMsg(GroupMsg msg, Sender sender) {     // 直接转发消息     sender.sendGroupMsg("群号", msg.getMsgContent()); }

**Comment by ForteScarlet** [comment]
参阅如下代码：
```java
@OnGroup
public void onMsg(GroupMsg msg, Sender sender, Getter getter) {
    // 得到 file 猫猫码中的 id
    final List<Neko> cats = msg.getMsgContent().getCats("file");
    if (cats.isEmpty()) {
        // not found.
        return;
    }
    // 拿到第一个
    final String fileId = cats.get(0).get("id");
    if (fileId == null) {
        return;
    }
    // 根据ID查询FileInfo
    final FileResult groupFile = getter.additionalExecute(new MiraiGroupFileByIdApi(msg.getGroupInfo().getGroupCodeNumber(), fileId, true));
    final FileInfo fileInfo = groupFile.getValue();
    // 得到文件URL
    final String url = fileInfo.getUrl();
    if (url == null) {
        return;
    }
    final String name = fileInfo.getName();
    final String fileCat = CatCodeUtil.INSTANCE
            .getStringCodeBuilder("file", true)
            // 上传到群文件的路径
            .key("path").value("/")
            // 文件url
            .key("url").value(url)
            // 文件名
            .key("fileName").value(name + "-cp")
            .build();

    // 发送到群
    // 注意，文件不支持私聊。
    sender.sendGroupMsg("目标群", fileCat);
}
```

**Comment by 930893138** [comment]
非常感谢，问题解决了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ForteScarlet/simpler-robot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月10日(星期六) 凌晨1:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ForteScarlet/simpler-robot] 2.0的情况下，我想用机器人转发别人发的（本地文件，非链接）文件， (Issue #450)





 
参阅如下代码：
 @OnGroup public void onMsg(GroupMsg msg, Sender sender, Getter getter) {     // 得到 file 猫猫码中的 id     final List<Neko&gt; cats = msg.getMsgContent().getCats("file");     if (cats.isEmpty()) {         // not found.         return;     }     // 拿到第一个     final String fileId = cats.get(0).get("id");     if (fileId == null) {         return;     }     // 根据ID查询FileInfo     final FileResult groupFile = getter.additionalExecute(new MiraiGroupFileByIdApi(msg.getGroupInfo().getGroupCodeNumber(), fileId, true));     final FileInfo fileInfo = groupFile.getValue();     // 得到文件URL     final String url = fileInfo.getUrl();     if (url == null) {         return;     }     final String name = fileInfo.getName();     final String fileCat = CatCodeUtil.INSTANCE             .getStringCodeBuilder("file", true)             // 上传到群文件的路径             .key("path").value("/")             // 文件url             .key("url").value(url)             // 文件名             .key("fileName").value(name + "-cp")             .build();     // 发送到群     // 注意，文件不支持私聊。     sender.sendGroupMsg("目标群", fileCat); }
