### ISSUE TITLE
Bot.getInstances()函数抛出FileNotFoundException

### ISSUE THREAD

**Issue by Enderman-Teleporting** [ForteScarlet/simpler-robot#464]
### 版本号

v2

### 问题描述

如上，缺少的是C:/Users/用户名/.accessibility.properties

### 复现方式

![5fdfca01ab99ed1e](https://user-images.githubusercontent.com/100068319/193789872-68b5f926-e5c7-40d4-92c4-24f0145bf4bd.png)
如图，通过debug发现是String bot=。。。那行

**Comment by Enderman-Teleporting** [comment]
2.4.0版本

**Comment by ForteScarlet** [comment]
请自行检查对应文件或文件路径是否存在。
且`Bot.getInstances()`并非simbot的api，大概率是mirai的。
