### ISSUE TITLE
请问v3.0 怎么合并消息 并发送？

### ISSUE THREAD

**Issue by madGodFucker** [ForteScarlet/simpler-robot#468]
### 版本号

v3.0.0

### 疑问描述

如标题

**Comment by ForteScarlet** [comment]
可以参考：
- #401  
- https://github.com/simple-robot/simbot-component-mirai/issues/56

**Comment by madGodFucker** [comment]
> 可以参考：
> 
> #401
> 
> [simple-robot/simbot-component-mirai#56](https://github.com/simple-robot/simbot-component-mirai/issues/56)

// 得到原始的消息链
                final MessageChain originalMessageChain = ((MiraiReceivedMessageContent) messageContent).getOriginalMessageChain();

originalMessageChain 有办法手动修改消息的内容吗

**Comment by ForteScarlet** [comment]
更多参考：
- https://github.com/simple-robot/simbot-component-mirai/pull/62

**Comment by madGodFucker** [comment]
> 

                        MessageChainBuilder messageChainBuilder = new MessageChainBuilder();
                        messageChainBuilder.add()
最后一个问题，想请教下messageChainBuilder.add() 有办法添加图片吗

**Comment by ForteScarlet** [comment]
> messageChainBuilder.add() 有办法添加图片吗

`MessageChainBuilder` 是mirai的API，不属于simbot，请自行参考mirai中 `Image` 的文档说明。
