### ISSUE TITLE
请问有办法 监听群里的消息撤回事件吗

### ISSUE THREAD

**Issue by madGodFucker** [ForteScarlet/simpler-robot#469]
### 版本号

v3.0.0

### 疑问描述

如题

**Comment by ForteScarlet** [comment]
在mirai中，你可以监听 `MiraiGroupMessageRecallEvent` 事件。

但是需要注意，直接监听事件是无法得到被撤回消息的**消息内容**内容的，需要配合配置属性 `config.recallMessageCacheStrategy` (参考[此处](https://component-mirai.simbot.forte.love/docs/bot-config#recallmessagecachestrategyconfiguration)中此属性的描述）

```json
{
  ...
  "config": {
      "recallMessageCacheStrategy": "MEMORY_LRU"
  }
}
```

在后续某次更新中，配置格式做了调整（文档尚未同步）

```json
{
  ...
  "config": {
    "recallMessageCacheStrategyConfig": {
       "type": "memory_lru"
   }
  }
}
```

此配置实现详情参考 [RecallMessageCacheStrategyConfiguration](https://github.com/simple-robot/simbot-component-mirai/blob/main/simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/bot/RecallMessageCacheStrategyConfiguration.kt) 。

其他参考：
- #417
- https://github.com/simple-robot/simbot-component-mirai/pull/75
- https://github.com/simple-robot/simbot-component-mirai/pull/39

**Comment by madGodFucker** [comment]
<dependency>
            <groupId>love.forte.simbot.component</groupId>
            <artifactId>simbot-component-mirai-boot</artifactId>
            <version>${simbot-component-mirai.version}</version>
        </dependency>    
<properties>
        <java.version>1.8</java.version>
        <simbot.version>3.0.0.preview.3.0</simbot.version>
        <simbot-component-tcg.version>${simbot.version}-0.6</simbot-component-tcg.version>
        <simbot-component-mirai.version>${simbot.version}-2100.0.1</simbot-component-mirai.version>
    </properties>
引入的该版本的mirai的依赖后， 没有MiraiGroupMessageRecallEvent 这个类[哭]

**Comment by ForteScarlet** [comment]
这个版本太低了，参考 [discussions#7](https://github.com/orgs/simple-robot/discussions/7) 给出的参考版本

**Comment by madGodFucker** [comment]
> 这个版本太低了，参考 [discussions#7](https://github.com/orgs/simple-robot/discussions/7) 给出的参考版本

        
        <dependency>
            <groupId>love.forte.simbot.boot</groupId>
            <artifactId>simboot-core-spring-boot-starter</artifactId>
            <version>3.0.0-beta.2</version>
        </dependency>

        
        <dependency>
            <groupId>love.forte.simbot.component</groupId>
            <artifactId>simbot-component-tencent-guild-boot</artifactId>
            <version>3.0.0.0-alpha.2</version>
        </dependency>

        
        <dependency>
            <groupId>love.forte.simbot.component</groupId>
            <artifactId>simbot-component-mirai-core</artifactId>
            <version>3.0.0.0-beta-M3</version>
        </dependency>
使用新版本后 很多注解不能用了。。 甚至 @EnableSimbot 也没了 [哭]

**Comment by ForteScarlet** [comment]
版本从 `preview` 到 `beta` 之间确实存在很多不兼容更新，但是并没有怎么调整过注解相关内容。如果是 `@EnableSimbot` 提示**过时**，是因为 `@EnableSimbot` 调整过一次包结构。如果是引用错误，比如找不到注解类，请检查依赖是否正确被解析/下载或参考 [这里](https://www.yuque.com/simpler-robot/simpler-robot-doc/rvsl9p)
