### ISSUE TITLE
请问如果我想同意好友申请时，同时为好友添加备注该如何操作呢?

### ISSUE THREAD

**Issue by darvenking** [ForteScarlet/simpler-robot#483]
### 版本号

3.0.0.preview.20.0

### 疑问描述

请问如果我想同意好友申请时，同时为好友添加备注该如何操作呢?
我把文档完整看了一遍，也看了代码，没找到相关操作方法
accpet()方法也不能传参

**Comment by ForteScarlet** [comment]
目前暂时没有为好友指定备注的能力，这要等待mirai的更新以及组件对mirai的升级

**Comment by darvenking** [comment]
ok，那我等待下
