### ISSUE TITLE
依赖未同步到中央仓库嘛，我引入依赖下载不了！

### ISSUE THREAD

**Issue by XM2510136957** [ForteScarlet/simpler-robot#492]
### 版本号

3.0

### 问题描述

依赖未同步到中央仓库嘛，我引入依赖下载不了！

### 复现方式

依赖无法引入

**Comment by ForteScarlet** [comment]
[Releases](https://github.com/simple-robot/simpler-robot/releases) 发布时会附带**仓库参考**可用于验证是否存在于仓库。
如果你使用了仓库镜像，可考虑移除镜像（例如阿里云镜像，它同步的比较缓慢）

**Comment by XM2510136957** [comment]
> [Releases](https://github.com/simple-robot/simpler-robot/releases) 发布时会附带**仓库参考**可用于验证是否存在于仓库。 如果你使用了仓库镜像，可考虑移除镜像（例如阿里云镜像，它同步的比较缓慢）

我未使用阿里云镜像，我用的默认的.

Could not find artifact love.forte.simbot.boot:simboot-core-spring-boot-starter:pom:3.0.0.beta.2 in central (https://repo.maven.apache.org/maven2)

**Comment by ForteScarlet** [comment]
很明显它是 [存在的](https://repo.maven.apache.org/maven2/love/forte/simbot/boot/simboot-core-spring-boot-starter/3.0.0-beta.2/)，请检查网络环境或各种相关配置

**Comment by ForliyScarlet** [comment]
此issue已经在「等待反馈」状态下5日未应答。如果在「陈旧」状态下逾期2日将会被视为无效过期并关闭。

**Comment by ForliyScarlet** [comment]
此issue已经在「陈旧」状态下逾期2日未应答, 视为无效过期并关闭。
