### ISSUE TITLE
Unable to find the com.charleskorn.kaml:kaml in current classpath, the bot configuration parser in *.bot.yaml format will not be available.

### ISSUE THREAD

**Issue by XM2510136957** [ForteScarlet/simpler-robot#495]
### 版本号

3.0

### 附加版本

Unable to find the com.charleskorn.kaml:kaml in current classpath, the bot configuration parser in *.bot.yaml format will not be available.

### 问题描述

Unable to find the com.charleskorn.kaml:kaml in current classpath, the bot configuration parser in *.bot.yaml format will not be available.

### 复现方式

![image](https://user-images.githubusercontent.com/18229485/200156711-f62324c7-134d-4f80-96b8-53a4c83e8a35.png)
![image](https://user-images.githubusercontent.com/18229485/200156719-9e2d5353-ca6d-483a-83f6-da78f8b8e41f.png)

**Comment by ForteScarlet** [comment]
这只是一个警告，如果你不打算使用 yml 配置可以无视它

**Comment by XM2510136957** [comment]
> 这只是一个警告，如果你不打算使用 yml 配置可以无视它

配置并未生效呀，项目启动就只有这个警告提示，没有机器人是否登录成功的提示。

**Comment by ForteScarlet** [comment]
properties解析器加载了，但是 yaml 解析器并未加载，也就是说并没有在环境中找到 kaml 依赖，尝试：
- 检查kaml依赖是否正确下载
- 尝试增加/移除 `<scope>runtime</scope>` 
- 尝试使用 Json 格式配置文件

**Comment by XM2510136957** [comment]
> > 这只是一个警告，如果你不打算使用 yml 配置可以无视它
> 
> 配置并未生效呀，项目启动就只有这个警告提示，没有机器人是否登录成功的提示。



> properties解析器加载了，但是 yaml 解析器并未加载，也就是说并没有在环境中找到 kaml 依赖，尝试：
> 
> * 检查kaml依赖是否正确下载
> * 尝试增加/移除 `<scope>runtime</scope>`
> * 尝试使用 Json 格式配置文件

只是用json格式可以，好像maria登录有点问题
![image](https://user-images.githubusercontent.com/18229485/200157387-30a3f775-8e1f-4830-8ff7-857ae19b9211.png)

**Comment by ForteScarlet** [comment]
see https://github.com/orgs/simple-robot/discussions/24

**Comment by ForliyScarlet** [comment]
此issue已经在「等待反馈」状态下5日未应答。如果在「陈旧」状态下逾期2日将会被视为无效过期并关闭。

**Comment by ForliyScarlet** [comment]
此issue已经在「陈旧」状态下逾期2日未应答, 视为无效过期并关闭。
