### ISSUE TITLE
qq版本过低

### ISSUE THREAD

**Issue by feiWoSCun** [ForteScarlet/simpler-robot#498]
### 版本号

2

### 问题描述

写好账号密码之后，登录之后出现qq版本过低问题，

### 复现方式

写好账号密码之后，登录

**Comment by ForteScarlet** [comment]
参考 https://github.com/orgs/simple-robot/discussions/24 ，v2版本更新到 `v2.5.0` 并修改登录协议为 `ANDROID_PAD` 或 `IPAD`

**Comment by ForliyScarlet** [comment]
此issue已经在「等待反馈」状态下5日未应答。如果在「陈旧」状态下逾期2日将会被视为无效过期并关闭。

**Comment by ForliyScarlet** [comment]
此issue已经在「陈旧」状态下逾期2日未应答, 视为无效过期并关闭。
