### ISSUE TITLE
mirai组件beta4版本启动失败

### ISSUE THREAD

**Issue by wuyou-123** [ForteScarlet/simpler-robot#499]
### 版本号

v3.0.0

### 附加版本

        <simbot-component-mirai.version>3.0.0.0-beta.4</simbot-component-mirai.version>

### 问题描述

![image](https://user-images.githubusercontent.com/69062567/200725523-1dd6854d-dd90-44eb-8c71-899758e31760.png)

### 复现方式

<properties>
        <java.version>1.8</java.version>
        <kotlin.version>1.6.21</kotlin.version>
        <simbot.version>3.0.0-M2</simbot.version>
        <simbot-component-mirai.version>3.0.0.0-beta.4</simbot-component-mirai.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>love.forte.simbot.boot</groupId>
            <artifactId>simboot-core-spring-boot-starter</artifactId>
            <version>${simbot.version}</version>
        </dependency>
        
        
        <dependency>
            <groupId>love.forte.simbot.component</groupId>
            <artifactId>simbot-component-mirai-boot</artifactId>
            <version>${simbot-component-mirai.version}</version>
        </dependency>
</dependencies>

**Comment by ForteScarlet** [comment]
参考 https://github.com/orgs/simple-robot/discussions/23
