### ISSUE TITLE
[QUE] mirai组件多行文本控制台显示不全

### ISSUE THREAD

**Issue by xzFB16A74EFFF04AF1006F040BE86D6262** [ForteScarlet/simpler-robot#50]
version: 2.0.0-RC.1`` 

module: `` 

## 问题描述

@Listen(GroupMsg.class)
    public void GroupMessage(GroupMsg msg,MsgSender sender){

        System.out.println(msg.getMsg());
    }

假设接收到一个换行群消息：
Test
Test
Test
通过System.out.println(msg.getMsg());仅能得到最后一个Test

## 复现方式

@Listen(GroupMsg.class)
    public void GroupMessage(GroupMsg msg,MsgSender sender){

        System.out.println(msg.getMsg());
    }

假设接收到一个换行群消息：
Test
Test
Test
通过System.out.println(msg.getMsg());仅能得到最后一个Test

**Comment by ForteScarlet** [comment]
试着`msg.getMsg().replaceAll("\r|\n", "")`，
并看看消息是否正常。如果消息正常， 那么说明只是因为mirai换行符导致的控制台输出不全，而不是真的消息缺失。
顺便，如果只是为了获取文本消息，建议使用`msg.getText`
