### ISSUE TITLE
提示扫码验证，验证完成后依然

### ISSUE THREAD

**Issue by minimoney12** [ForteScarlet/simpler-robot#506]
### 版本号

v2.4.0

### 疑问描述

![image](https://user-images.githubusercontent.com/78300553/201832730-a4886a40-dd3f-44f0-9c7a-aa972543c04a.png)

![image](https://user-images.githubusercontent.com/78300553/201832855-b19fff00-386d-492d-af48-fccdffbdc69f.png)

验证完成后回到程序依然会提示要求验证

**Comment by ForteScarlet** [comment]
参考 #438

**Comment by ForliyScarlet** [comment]
此issue已经在「等待反馈」状态下5日未应答。如果在「陈旧」状态下逾期2日将会被视为无效过期并关闭。

**Comment by ForliyScarlet** [comment]
此issue已经在「陈旧」状态下逾期2日未应答, 视为无效过期并关闭。
