### ISSUE TITLE
是否支持发送json或xml卡片消息？

### ISSUE THREAD

**Issue by 954L** [ForteScarlet/simpler-robot#525]
### 版本号

v3.0.0-M2

### 疑问描述

看了`love.forte.simbot.message`包下只有`At`,`AtAll`,`Face`...这些，没找到xml跟json的相关message。
想问下现在是否支持发此类消息呢？支持的话具体是哪个类？

还有一个`net.mamoe.mirai.message.data`包下的`XmlMessageBuilder`类，这个类能用来发xml吗？可否举例一下？万分感谢！

**Comment by ForteScarlet** [comment]
没有对这类消息的直接包装，考虑直接使用mirai自身的类型，比如 `net.mamoe.mirai.message.data.ServiceMessage` 及其相关类型。它们的使用方式参考它们的文档注释或mirai自己的相关文档。

Java 中可以通过 `MiraiMessageParserUtil.asSimbotMessage(...)` 将Mirai的消息对象转化为Simbot中的 `Message.Element` 对象类型。

**Comment by 954L** [comment]
> 没有对这类消息的直接包装，考虑直接使用mirai自身的类型，比如 `net.mamoe.mirai.message.data.ServiceMessage` 及其相关类型。它们的使用方式参考它们的文档注释或mirai自己的相关文档。
> 
> Java 中可以通过 `MiraiMessageParserUtil.asSimbotMessage(...)` 将Mirai的消息对象转化为Simbot中的 `Message.Element` 对象类型。

可以了，谢谢。
