### ISSUE TITLE
GroupMember类是没有踢出成员的函数吗？

### ISSUE THREAD

**Issue by 954L** [ForteScarlet/simpler-robot#527]
### 版本号

v3.0.0-M2

### 疑问描述

![QQ图片20221201222206](https://user-images.githubusercontent.com/35250721/205080716-c66fef1b-c60d-4c1c-b480-ea4f2347dce4.png)

`MiraiMember`类的话是有`kickBlocking`函数的，强转之后也是可以用的。
但是其他禁言解禁都有，就唯独比`MiraiMember`少了踢人的函数，是漏了吗？

**Comment by ForteScarlet** [comment]
`GroupMember` 目前不会默认实现 `DeleteSupport` ，它会在支持的情况下由组件自行决定是否实现，就比如 `MiraiMember`。`kick` 与 `delete` 在mirai组件中是等效的。
