### ISSUE TITLE
实现 AnnotationEventFilterFactory 的时候 无法在内部类中注入组件

### ISSUE THREAD

**Issue by nosoul-nyl** [ForteScarlet/simpler-robot#543]
### 版本号

3.0.0-M5

### 问题描述

https://gitee.com/nosoull/graduation-design-from-nyl/blob/master/src/main/java/com/tuanzijx/simbot/graduationdesignfromnyl/filterCfg/OnTheFunctionFilterFactory.java

当我使用装配组件的方式去配置
![image](https://user-images.githubusercontent.com/62659004/207506814-e6d30e68-1768-438f-8d7c-4af0192bef2b.png)
配置不起作用  控制台也不显示报错

当我尝试去new这个内部类的时候 
![image](https://user-images.githubusercontent.com/62659004/207507128-a89c7cb0-7135-4d57-9848-78ae56ca7695.png)
控制台显示 ![image](https://user-images.githubusercontent.com/62659004/207507930-a992065d-5e30-49d1-972a-07add8985672.png)  但是在其他地方可以正常的注入和使用 OnthefunctiontableService

### 复现方式

在问题描述中 提供了gitee地址  已开源

**Comment by ForteScarlet** [comment]
`Filter.by` 的解析似乎存在问题或被遗漏。

临时解决办法：可暂时通过拦截器代替过滤器

```java
@Component
public class MyInterceptor implements AnnotatedBlockingEventListenerInterceptor {


    @NotNull
    @Override
    public EventResult doIntercept(@NotNull Context context) {
        boolean ok = true;

        // ...

        if (ok) {
            // 如果放行，类似于filter中的return true
            return context.proceedBlocking();
        } else {
            // 不放行，类似于filter中的return false
            return EventResult.invalid();
        }
    }
}
```
```java
    @Interceptor(type = MyInterceptor.class)
    @Listener
    public void onEvent(...) {
        ...
    }
```

**Comment by nosoul-nyl** [comment]
> ```java
> 类似于filter中的return f
> ```

好的  感谢感谢

**Comment by nosoul-nyl** [comment]
> ```java
> context
> ```

依旧显示
![image](https://user-images.githubusercontent.com/62659004/207540735-8e096dfc-51c4-4da2-96ce-5c365f98ff44.png)

OnthefunctiontableService 这个类已经测试过没有问题了
![image](https://user-images.githubusercontent.com/62659004/207540992-84e181b3-668e-4b1c-bfea-797ef3c35e49.png)

下面是我定义的拦截器 和 在方法上使用注解
![image](https://user-images.githubusercontent.com/62659004/207541251-b1636480-9929-405a-9a27-a2491f25ff4f.png)
![image](https://user-images.githubusercontent.com/62659004/207541434-0051b109-e702-4be8-9700-60355b128793.png)

**Comment by ForteScarlet** [comment]
使用快照版本 `3.0.0-M6-SNAPSHOT` 并再尝试使用过滤器或拦截器

**Comment by nosoul-nyl** [comment]
> 使用快照版本 `3.0.0-M6-SNAPSHOT` 并再尝试使用过滤器或拦截器

拦截器可以正常使用了   过滤器依旧是上述问题。

还有一个问题就是
当我一开始使用快照版本时有一个报错   ‘The bean 'xxxxxxx', could not be registered’
为了运行  我在我的yml文件中添加了   
spring:
  main:
    allow-bean-definition-overriding: true

只是因为我使用了快照版本的原因嘛

**Comment by ForteScarlet** [comment]
> 当我一开始使用快照版本时有一个报错 ‘The bean 'xxxxxxx', could not be registered’

仅凭这一句话无法确定任何信息

**Comment by ForteScarlet** [comment]
本地测试暂未复现过滤器失效，但是存在已知问题。尝试在一个类中**只保留一个监听函数**后再尝试过滤器。

> ‘The bean 'xxxxxxx#GENERATED_LISTENER', could not be registered’

此问题会在下次快照刷新时修复

**Comment by nosoul-nyl** [comment]
> 本地测试暂未复现过滤器失效，但是存在已知问题。尝试在一个类中**只保留一个监听函数**后再尝试过滤器。
> 
> > ‘The bean 'xxxxxxx#GENERATED_LISTENER', could not be registered’
> 
> 此问题会在下次快照刷新时修复

感谢帮助  过滤器可以使用了   是我自己写bug了
