### ISSUE TITLE
遇到提示QQ版本过低怎么解决的

### ISSUE THREAD

**Issue by xiaosajie08** [ForteScarlet/simpler-robot#547]
### 版本号

遇到提示QQ版本过低怎么解决的

### 疑问描述

遇到提示QQ版本过低怎么解决的

**Comment by ForteScarlet** [comment]
参考[社区中各相关问题](https://github.com/orgs/simple-robot/discussions?discussions_q=QQ%E7%89%88%E6%9C%AC%E8%BF%87%E4%BD%8E)
