### ISSUE TITLE
simpler-robot是否可以可以使用mirai的插件

### ISSUE THREAD

**Issue by nitianxpy** [ForteScarlet/simpler-robot#571]
### 版本号

3.0.0-M6

### 疑问描述

mirai提供了一个登录验证的插件，可以方便登录，插件类型为jar包，如何集成到我的springboot项目中了，或者说目前不支持后续会支持这个功能了

**Comment by ForteScarlet** [comment]
理论上可以，但实际上不可用。mirai的插件据我所知是需要在mcl环境中使用的，但是simbot的mirai组件仅依赖了 `mirai-core` ，并不使用mcl。

**Comment by nitianxpy** [comment]
了解
