### ISSUE TITLE
GroupMemberDecreaseEvent 监听不到退群事件

### ISSUE THREAD

**Issue by nosoul-nyl** [ForteScarlet/simpler-robot#573]
### 版本号

3.0.0-M6

### 附加版本

		
		<dependency>
			<groupId>love.forte.simbot.boot</groupId>
			<artifactId>simboot-core-spring-boot-starter</artifactId>
			<version>3.0.0-M6-SNAPSHOT</version>
		</dependency>

		
		<dependency>
			<groupId>love.forte.simbot.component</groupId>
			<artifactId>simbot-component-mirai-core</artifactId>
			<version>3.0.0.0-beta.6</version>
		</dependency>

### 问题描述

   
在下面这个方法中使用GroupMemberDecreaseEvent作为参数时不能监听到退群事件，当使用 MemberDecreaseEvent 作为参数时可以监听到退群事件。 
```
 @Listener
    public void groupMemberDecrease(GroupMemberDecreaseEvent groupMemberDecreaseEvent){

        System.out.println("进入");
//        String groupId = groupMemberDecreaseEvent.getOperator().getId().toString();
        String groupId = groupMemberDecreaseEvent.getGroup().getId().toString();
        String nickOrUsername = groupMemberDecreaseEvent.getMember().getNickOrUsername();}
```
### 复现方式

代码在问题描述中

**Comment by ForteScarlet** [comment]
GroupMemberDecreaseEvent 暂时未被支持，~~然后就被忘了~~ ，直接使用 MemberDecreaseEvent 即可。

**Comment by nosoul-nyl** [comment]
> GroupMemberDecreaseEvent 暂时未被支持，~然后就被忘了~ ，直接使用 MemberDecreaseEvent 即可。

新年快乐，感谢回复

**Comment by ForteScarlet** [comment]
同乐同乐
