### ISSUE TITLE
多个机器人可否互不影响

### ISSUE THREAD

**Issue by 954L** [ForteScarlet/simpler-robot#579]
### 建议描述

比方说我配置了多个bot，在启动项目时如果有一个bot无法登陆（密码错误、冻结...等）都会阻塞其他bot，导致无法bot无法正常登陆。
同理项目正常运行中，若多个bot中有一个bot异常（被顶下线、密码修改、冻结...等）都会导致所有bot全部都无法正常收发消息。

**Comment by ForteScarlet** [comment]
> 在启动项目时如果有一个bot无法登陆（密码错误、冻结...等）都会阻塞其他bot，导致无法bot无法正常登陆。

正常情况下如果个别bot登录流程失败，理应是直接抛出异常而非**阻塞**。如果希望登录过程中个别bot的登录失败不会直接抛出异常，追踪 #580 ，目前可以通过关闭`自动启动bot`的选项并自行手动启动它们来达到精准控制。

> 项目正常运行中，若多个bot中有一个bot异常（被顶下线、密码修改、冻结...等）都会导致所有bot全部都无法正常收发消息

此问题未复现。复现环境：
- simbot `v3.0.0-RC.2`
- simbot-mirai `v3.0.0-M4`

如果你的环境版本较低，优先尝试更新版本。如果仍有此问题，提供详细的版本信息以及日志信息进行反馈。

**Comment by ForliyScarlet** [comment]
此issue已经在「等待反馈」状态下5日未应答。如果在「陈旧」状态下逾期2日将会被视为无效过期并关闭。
