### ISSUE TITLE
请问如何在v3中解析转发的b站视频的信息

### ISSUE THREAD

**Issue by strll** [ForteScarlet/simpler-robot#582]
### 版本号

v3.0.0-M2

### 疑问描述

我不知道如何从GroupMessageEvent event这个对象中解析出转发的b站视频的地址和封面地址

**Comment by ForteScarlet** [comment]
**b站视频** 的分享消息通常是一种小程序，而在mirai中小程序消息一般属于 [富文本消息](https://kdoc.mirai.mamoe.net/2.13.4/mirai-core-api/net.mamoe.mirai.message.data/-rich-message/index.html) 。在simbot组件中没有对于富文本消息的直接解析封装，因此需要通过 [SimbotOriginalMiraiMessage](https://docs.simbot.forte.love/components/mirai/simbot-component-mirai-core/love.forte.simbot.component.mirai.message/-simbot-original-mirai-message/index.html) 来获取。

```
// 伪代码
if (message is SimbotOriginalMiraiMessage) {
    if (message.originalMiraiMessage is RichMessage) {
        // 获取信息
    }
}
```

至于内容，请根据得到的内容格式自行尝试解析，这与框架本身无关。

**Comment by ForliyScarlet** [comment]
此issue已经在「等待反馈」状态下5日未应答。如果在「陈旧」状态下逾期2日将会被视为无效过期并关闭。
