### ISSUE TITLE
在v3中，如何进行消息转发

### ISSUE THREAD

**Issue by fhh-coder** [ForteScarlet/simpler-robot#591]
### 版本号

v3.0.0

### 选择此问题涉及的编程语言

Java

### 选择此问题涉及的组件库

其他

### 疑问描述

在v2中，我是使用的Sender 进行消息转发，比如群聊消息转发给另外一个qq/qq群，或者私聊消息转发给qq/qq群。
在v3中，我不知道如何进行消息转发。

**Comment by ForteScarlet** [comment]
https://github.com/simple-robot/simbot-component-mirai/issues/56

**Comment by ForteScarlet** [comment]
哦消息转发不是合并转发，不好意思看错了，参考此图
![`IW$673E$YR3{OO945@@3CT](https://user-images.githubusercontent.com/40045247/218311865-0b68d459-0088-4cce-bfb6-b2f6aeb89367.jpg)
