### ISSUE TITLE
v3  Java怎么主动退群与申请加群？

### ISSUE THREAD

**Issue by GTX-Yang** [ForteScarlet/simpler-robot#601]
### 版本号

Mirai：3.0.0.0-M5  Simbot：3.0.0-M6

### 选择此问题涉及的编程语言

Java

### 选择此问题涉及的组件库

mirai

### 疑问描述

v3  Java怎么主动退群与申请加群？
找了很久，只有简单的两句话......学习有点困难

**Comment by ForteScarlet** [comment]
mirai 组件中退群使用 [`MiraiGroup.delete`](https://docs.simbot.forte.love/components/mirai/simbot-component-mirai-core/love.forte.simbot.component.mirai/-mirai-group/delete.html)

当不直接使用mirai组件相关对象时，需要判断类型后操作
```java
if (group instanceof MiraiGroup miraiGroup) {
    miraiGroup.deleteBlocking();
}
```

mirai不支持主动加群。
