### ISSUE TITLE
在使用announcements.getBlocking方法时候通过fid获取群告报错

### ISSUE THREAD

**Issue by yujumpjump** [ForteScarlet/simpler-robot#602]
### 版本号

3.0.0.0-M5

### 涉及的编程语言

Java

### 项目构建工具

Maven

### 涉及的组件库

mirai (QQ)

### 问题描述

在使用announcements.getBlocking方法时候通过fid获取群告报错

### 复现方式

   MiraiAnnouncements announcements = group.getAnnouncements();
    
    MiraiOnlineAnnouncement blocking = announcements.getBlocking("36ee6e2800000000742cc963d7e90900"); 

    List<MiraiMember> miraiMembers = blocking.membersBlocking(true);

    for (MiraiMember miraiMember:miraiMembers){
        System.out.println(miraiMember);
    }
}

### 相关日志

```Text
// Field 'msg' is required for type with serial name 'net.mamoe.mirai.internal.contact.announcement.GroupAnnouncement', but it was missing
```

**Comment by ForteScarlet** [comment]
疑似mirai的bug，等待其官方反馈

see https://github.com/mamoe/mirai/issues/2509
