### ISSUE TITLE
simbot.bot-configuration-resources可否支持配置磁盘文件路径？

### ISSUE THREAD

**Issue by 954L** [ForteScarlet/simpler-robot#603]
### 建议描述

配置项目resource下一切正常，但是无法配置至磁盘目录。
```bash
17:34:47.376 [main] WARN  l.f.s.b.StandardBotVerifyInfoDecoderFactory - Unable to find the com.charleskorn.kaml:kaml in current classpath, the bot configuration parser in *.bot.yaml format will not be available.
17:34:47.376 [main] WARN  l.f.s.b.StandardBotVerifyInfoDecoderFactory - Unable to find the kotlinx-serialization-properties in current classpath, the bot configuration parser in *.bot.properties format will not be available.
17:34:47.380 [main] WARN  l.f.s.s.a.SimbotSpringBootBotAutoRegisterBuildConfigure - Can not resolve resource path 「/data/qq-bot/bots/1/*.bot*」: class path resource [data/qq-bot/bots/1/] cannot be resolved to URL because it does not exist, just use empty resources.
```

因为有时候要改一些配置啥的，就不用重新打包项目，直接修改配置文件后重启即可，会更方便些

**Comment by ForteScarlet** [comment]
Duplicate of #503

**Comment by 954L** [comment]
@ForteScarlet 亲测不可用，绝对路径跟相对路径都试过，linux跟windows都试过。均不可用
```bash
bot配置文件：xxx.bot.json
# 尝试过以下路径
file:/data/bots/*.bot*
file:/data/bots/*.json
file:bots/*.bot*
```

**Comment by ForteScarlet** [comment]
本地测试可用。

spring `application.properties`: 

```properties 
simbot.bot-configuration-resources[0]=file:bots/*.bot
```
目录结构：

```
project
    \-- bots
    |       \-- xxx.bot
    \-- src
           \-- main
                  \-- java
                  \-- resources
```

如果依旧不行，请提供相关文件目录、配置文件等内容。

**Comment by 954L** [comment]
> 本地测试可用。
> 
> spring `application.properties`:
> 
> ```ini
> simbot.bot-configuration-resources[0]=file:bots/*.bot
> ```
> 
> 目录结构：
> 
> ```
> project
>     \-- bots
>     |       \-- xxx.bot
>     \-- src
>            \-- main
>                   \-- java
>                   \-- resources
> ```
> 
> 如果依旧不行，请提供相关文件目录、配置文件等内容。

可以了谢谢，linux是因为我用docker，忘记映射了。本地是文件分隔符弄错了，还有放到了resouces下

**Comment by twwch** [comment]
我也是用的docker启动，但是目录挂在无效，无法识别到机器人的配置文件

**Comment by twwch** [comment]
我也是用的docker启动，但是目录挂在无效，无法识别到机器人的配置文件


Dockerfile
```
FROM openjdk:17-oracle
ADD target/qq-robot-1.0-SNAPSHOT.jar app.jar
RUN bash -c 'touch /app.jar'
WORKDIR /app
VOLUME ["/app/bots"]
ENTRYPOINT 9543
ENTRYPOINT ["java", "-Dfile.encoding=utf-8", "-Djava.security.edg=file:/dev/./urandom", "-Duser.timezone=Asia/Shanghai", "-Xmx128m", "-Xms64m", "-jar", "/app.jar"]
```

运行的命令：
```
docker run -it -m 1800m  --restart=always -d --name qq-robot-chatgpt \
        -v /etc/hosts:/etc/hosts \
        -v /var/qq-robot/:/app/bots \
        -v /etc/localtime:/etc/localtime \
        -p  9543:9543 \
        -e LANG="en_US.UTF-8" \
        twwch/qq-chat-gpt:master
```

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/44161003/222897042-9c2cd2dc-d6bc-4501-bd49-d1bd303e7848.png">

进入容器看，文件确实存在
<img width="448" alt="image" src="https://user-images.githubusercontent.com/44161003/222897239-69457a7e-80ce-4c5a-bc19-d9e201ab3c59.png">

**Comment by twwch** [comment]
@954L 请教一下

**Comment by twwch** [comment]
@ForteScarlet 能否帮忙看下呢？

**Comment by ForteScarlet** [comment]
> @ForteScarlet 能否帮忙看下呢？

@twwch 我不会用docker

**Comment by 954L** [comment]
> @954L 请教一下

那你的配置文件指向：`file:/app/bots/*.json`，这个不行吗

**Comment by 954L** [comment]
@twwch

**Comment by twwch** [comment]
> 

不行，能否看下你的dockerfile和运行命令么？

**Comment by 954L** [comment]
@twwch 
**Dockerfile**
```shell
#FROM jdk8-alpine:v1.8.0_192
#FROM openjdk:8-jdk-alpine
FROM frolvlad/alpine-oraclejre8
ADD qq-bot.jar qq-bot.jar
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone
#RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
# ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=pro", "/qq-bot.jar", "--server.ip=172.17.0.2", "--redis.ip=172.17.0.2"]
```

**shell**
```bash
docker run -d --name qq-bot-$1 \
-u root --restart=on-failure:3 --privileged \
-p 909$1:909$1 \
-v $(which docker):/usr/bin/docker \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /data/qq-bot/qq-bot:/qq-bot -v /data/sharedata/:/sharedata -v /data/qq-bot/bots:/bots \
-v /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime \
-it qq-bot-$1:1.0 java -server -Xms1024m -Xmx4096m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=2048m -jar -Dspring.profiles.active=pro$1 /qq-bot.jar
```

**Comment by twwch** [comment]
> @twwch **Dockerfile**
> 
> ```shell
> #FROM jdk8-alpine:v1.8.0_192
> #FROM openjdk:8-jdk-alpine
> FROM frolvlad/alpine-oraclejre8
> ADD qq-bot.jar qq-bot.jar
> RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone
> #RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
> # ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=pro", "/qq-bot.jar", "--server.ip=172.17.0.2", "--redis.ip=172.17.0.2"]
> ```
> 
> **shell**
> 
> ```shell
> docker run -d --name qq-bot-$1 \
> -u root --restart=on-failure:3 --privileged \
> -p 909$1:909$1 \
> -v $(which docker):/usr/bin/docker \
> -v /var/run/docker.sock:/var/run/docker.sock \
> -v /data/qq-bot/qq-bot:/qq-bot -v /data/sharedata/:/sharedata -v /data/qq-bot/bots:/bots \
> -v /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime \
> -it qq-bot-$1:1.0 java -server -Xms1024m -Xmx4096m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=2048m -jar -Dspring.profiles.active=pro$1 /qq-bot.jar
> ```

谢谢，我也已经跑起来了
