### ISSUE TITLE
code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。

### ISSUE THREAD

**Issue by pure-love-soldier** [ForteScarlet/simpler-robot#606]
### 版本号

v3.0.0.0-RC.3

### 涉及的编程语言

Java

### 项目构建工具

Maven

### 涉及的组件库

mirai (QQ)

### 问题描述

在尝试登录的时候提示我Error(bot=Bot(2531712479), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)

### 复现方式

![image](https://user-images.githubusercontent.com/126187045/221102823-a87a080d-69af-4f90-84f7-2135d085df90.png)

**Comment by ForteScarlet** [comment]
https://github.com/mamoe/mirai/issues/2524

**Comment by twwch** [comment]
有解决方案么？卡很久了

**Comment by ForteScarlet** [comment]
> 有解决方案么？卡很久了

[如上参考](https://github.com/simple-robot/simpler-robot/issues/606#issuecomment-1442850857)，追踪mirai的解决情况并尝试讨论中出现的各种方案。这可能是新的风控形式。

其他参考：
- https://github.com/mamoe/mirai/issues/2538

**Comment by twwch** [comment]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/44161003/222041086-2272c47f-64dc-40ad-b0a8-32523892d18c.png">
在账号配置下加上这个配置就行，我就是这样解决的

**Comment by pure-love-soldier** [comment]
是的，已解决，切换config.protocol就行

**Comment by Xiyujiang0203** [comment]
config.protocol在哪

**Comment by healinshadow** [comment]
請問Code45禁止登陸怎麽解決呀？

**Comment by YiMengYanYu** [comment]
我切换config.protocol然后变成code=237报错

**Comment by ForteScarlet** [comment]
@YiMengYanYu  mirai目前建议 `protocol` 手表相关协议，并且登录方式 `authorization.type` 更改为二维码扫码 `qr_code` ，(参考 [文档](https://component-mirai.simbot.forte.love/docs/bot-config/#%E9%85%8D%E7%BD%AE))，这样就**有概率** 可以使用，但无法保证稳定性。
