### ISSUE TITLE
换到simbot-component-mirai-core:3.0.0.0-M5后无法导入依赖

### ISSUE THREAD

**Issue by Bread-NiceCat** [ForteScarlet/simpler-robot#608]
### 版本号

simbot-component-mirai-core:3.0.0.0-M5

### 附加版本

simbot-core:3.0.0-RC.3
simbot-component-mirai-core:3.0.0.0-M5

### 涉及的编程语言

Java

### 项目构建工具

Gradle

### 涉及的组件库

mirai (QQ)

### 问题描述

无法导入mirai依赖库。经测试，非网络连通性问题
> repositories {
    maven{url="https://maven.aliyun.com/repository/public"}
    mavenCentral()
}
dependencies {
    implementation 'love.forte.simbot:simbot-core:3.0.0-RC.3'
    implementation 'love.forte.simbot.component:simbot-component-mirai-core:3.0.0.0-M5'
}

### 复现方式

-

### 相关日志

```Text
SSRobot:test: Could not resolve net.mamoe:mirai-core-api:2.14.0.
Required by:
    project : > love.forte.simbot.component:simbot-component-mirai-core:3.0.0.0-M5 > net.mamoe:mirai-core-jvm:2.14.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by Bread-NiceCat** [comment]
项目开源：https://gitee.com/Bread_NiceCat/ssrobot

**Comment by ForteScarlet** [comment]
如果仅是无法 import，参考 https://simbot.forte.love/faq/%E5%8C%85%E5%BC%95%E7%94%A8%E5%BC%82%E5%B8%B8/

**Comment by ForteScarlet** [comment]
> Required by:
    project : > love.forte.simbot.component:simbot-component-mirai-core:3.0.0.0-M5 > net.mamoe:mirai-core-jvm:2.14.0

疑似找不到 `mirai-core-api` 依赖，但是此依赖很明显是 [存在的](https://repo1.maven.org/maven2/net/mamoe/mirai-core-api/2.14.0/) ，尝试 _检查并清理本地maven仓库_、_更换仓库源比如移除aliyun镜像_ 等操作

**Comment by ForteScarlet** [comment]
值得注意的是，mirai官方的 [文档](https://github.com/mamoe/mirai/blob/dev/docs/ConfiguringProjects.md#gradle-groovy-dsl) 中提到，如果使用 `Gradle` 配置项目环境，则需要添加 `Kotlin` 插件（尽管不使用 `Kotlin` 开发）。
这一点比较容易被忽视，毕竟mirai-core是基于多平台的，因此也可以通过添加 `Kotlin` 插件来尝试解决此问题：

```groovy
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.8.10' // simbot 目前依赖Kotlin 1.8.10, mirai 目前似乎依赖 1.7.10
}
```

**Comment by ForliyScarlet** [comment]
此issue已经在「等待反馈」状态下5日未应答。如果在「陈旧」状态下逾期2日将会被视为无效过期并关闭。

**Comment by ForliyScarlet** [comment]
此issue已经在「陈旧」状态下逾期2日未应答, 视为无效过期并关闭。
