### ISSUE TITLE
无法触及监听

### ISSUE THREAD

**Issue by yujumpjump** [ForteScarlet/simpler-robot#609]
### 版本号

3.0.0.0-M5

### 涉及的编程语言

Java

### 项目构建工具

Maven

### 涉及的组件库

mirai (QQ)

### 问题描述

在没有使用任何过滤注解的时候 可以监听到其他群，但是会有其他群监听不到（不会触发事件）不是风控   因为其他群里面可以正常发送消息，

### 复现方式

    @Listener
    @Filters(value = {
            @Filter(value = "被踢",matchType = MatchType.TEXT_CONTAINS),
            @Filter(value = "注册",matchType = MatchType.TEXT_CONTAINS)
    })
    public void  onKeyword(MiraiGroupMessageEvent event){
        LongID id = event.getAuthor().getId();
        System.out.println(event.getAuthor().getNickname());
        // 获取 关键字
        String keyWord = event.getMessageContent().getPlainText();
        if(keyWord.contains("被踢")){
            event.getGroup().sendBlocking("pb="+event.getAuthor().getNickname());
        }else {
            try {
//                PathResource resource = Resource.of(Paths.get("C:\\Users\\ghost\\Desktop\\jumpjump bot\\img\\reg.jpg"));
                PathResource resource = Resource.of(Paths.get("C:\\Users\\admin\\Desktop\\img\\reg.jpg"));
                ResourceImage resourceImage = Image.of(resource);
                Messages elements = Messages.toMessages(new At(id), Text.of("\n注册如下图\n")).plus(Messages.toMessages(resourceImage));
                event.getGroup().sendBlocking(elements);
            } catch (RuntimeException e) {
                e.printStackTrace();
                event.getGroup().sendBlocking("注册图片消失了...@管理员检查！");
            }
        }
    }

**Comment by ForteScarlet** [comment]
在 [MiraiBotImpl.kt#L324](https://github.com/simple-robot/simbot-component-mirai/blob/876a59acef4e1c85d89c1718a42f5b872351248e/simbot-component-mirai-core/src/main/kotlin/love/forte/simbot/component/mirai/internal/MiraiBotImpl.kt#L324) 处和 [SimpleEventListenerManagerImpl.kt#L283](https://github.com/simple-robot/simpler-robot/blob/64e2e7fc4911fe78a6c52f627d1a120dbebc13bc/simbot-core/src/main/kotlin/love/forte/simbot/core/event/SimpleEventListenerManagerImpl.kt#L283) 增加断点以调试，如果在前者就没有事件，则说明mirai本身即无法收到此事件。

**Comment by ForteScarlet** [comment]
同时开启debug日志、mirai的网络日志（不确定等级，可能是trace或debug级别的日志）等各种调试信息，观察它们的信息

**Comment by ForliyScarlet** [comment]
此issue已经在「等待反馈」状态下5日未应答。如果在「陈旧」状态下逾期2日将会被视为无效过期并关闭。

**Comment by ForliyScarlet** [comment]
此issue已经在「陈旧」状态下逾期2日未应答, 视为无效过期并关闭。
