### ISSUE TITLE
originalAnnouncements.toList() 获取的数量为0

### ISSUE THREAD

**Issue by yujumpjump** [ForteScarlet/simpler-robot#619]
### 版本号

3.0.0.0-M5

### 涉及的编程语言

Java

### 项目构建工具

Maven

### 涉及的组件库

mirai (QQ)

### 问题描述

在使用originalAnnouncements.toList()获取公告的数量的时候  获取的数量为0，（是有公告的前提）

### 复现方式

        MiraiGroup group = miraiGroupMessageEvent.getGroup();
        MiraiAnnouncements announcements = group.getAnnouncements();
        Announcements originalAnnouncements = announcements.getOriginalAnnouncements();
        List<OnlineAnnouncement> onlineAnnouncements = originalAnnouncements.toList();
        log.info("公告数量{}",onlineAnnouncements.size());

**Comment by ForteScarlet** [comment]
本地测试未复现。

提供更详细的信息，包括debug日志、使用场景，以及是所有群都这样还是个别特殊群等。

`announcements.getOriginalAnnouncements()` 得到的结果最终为 mirai 自身的原生对象。如果能确保直接通过它们的API无法获取到列表（以及数量），可考虑反馈到[它们的issues](https://github.com/mamoe/mirai/issues)。

**Comment by yujumpjump** [comment]
已经获取到了 可能是因为我刚刚创建的群

**Comment by yujumpjump** [comment]
这个问题又出现了

**Comment by yujumpjump** [comment]
我测试的这个群他是一个大群 里面是有公告的，有时候获取不到 有时候就可以获取到

**Comment by ForteScarlet** [comment]
大概率与 https://github.com/mamoe/mirai/pull/2512 有关。
可以等待mirai的更新，或者将问题反馈到[它们的issues](https://github.com/mamoe/mirai/issues)。
