### ISSUE TITLE
originalAnnouncements.toList() 返回的集合有时为空

### ISSUE THREAD

**Issue by yujumpjump** [ForteScarlet/simpler-robot#629]
### 版本号

3.0.0.0-M5

### 附加版本

mirai 2.15.0-M1

### 涉及的编程语言

Java

### 项目构建工具

Maven

### 涉及的组件库

mirai (QQ)

### 问题描述

我没有过滤任何群自己来获取所有的群公告，而且群里面是有很多群公告的，有时候能获取 有时候获取的为空，

### 复现方式

  MiraiGroup group = miraiGroupMessageEvent.getGroup();
        /*-------------------------获取公告-----------------------------*/
        MiraiAnnouncements announcements = group.getAnnouncements();
        Announcements originalAnnouncements = announcements.getOriginalAnnouncements();
        System.out.println(originalAnnouncements.toList());

**Comment by ForteScarlet** [comment]
Duplicate of #619
