### ISSUE TITLE
如何主动发送私聊信息，以及获取消息中的图片原始url

### ISSUE THREAD

**Issue by mashiro-hjl** [ForteScarlet/simpler-robot#645]
### 版本号

v3.0.0-RC.3

### 涉及的编程语言

Java

### 涉及的组件库

mirai(QQ)

### 疑问描述

请问如何主动的向指定qq发送信息，我翻了一遍文档和Issue好像也没看到，以及如何获取到消息中的图片url，在v2.x版本中可以通过事件的msg中可以查看到，在3.0版本看不到url的信息，只有mirai的图片id。或者是有方法可以通过mirai的图片id进行发送？

**Comment by ForteScarlet** [comment]
> 1. 如何主动的向指定qq发送信息

主动发送消息参考 https://github.com/orgs/simple-robot/discussions/74 ，向指定用户发送消息，以群成员为例，先获取群，再获取成员：
```java
Member member = event.getGroup().getMember(xxxID); // nullable
member.sendBlocking(...);
```

bot的联系人（好友）则：
```java
Contact contact = bot.getContact(xxxID); // nullable
contact.sendBlocking(...);
```

> 2. 如何获取到消息中的图片url

参考 https://github.com/orgs/simple-robot/discussions/15 ，同时在类型判断那里，如果明确是要mirai的图片，可以缩小类型范围：
```java
if (message instanceof MiraiImage) {
        // 这个message是mirai中得到的图片
}
```

如果想获取真实链接，则：

```java
String url = miraiImage.queryUrlBlocking();
```

如果只是为了转发一个图片，则可以考虑直接发送 `Image` 对象而不需要查询URL。

```java
Image<?> image = ...;
Member member = ...;
member.sendBlocking(image);
```

**Comment by mashiro-hjl** [comment]
非常感谢你的回答，我的问题已解决。
