### ISSUE TITLE
版本过低导致无法登录

### ISSUE THREAD

**Issue by trueaseYUKI** [ForteScarlet/simpler-robot#656]
### 版本号

v3.0.0.RC

### 涉及的编程语言

Java

### 疑问描述

net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(3228256448), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)

**Comment by ForteScarlet** [comment]
https://github.com/mamoe/mirai/issues/2570

需要等待mirai的更新

**Comment by LYF-Uaena** [comment]
我也遇到了这个问题，在等更新
