### ISSUE TITLE
请在手机端使用请求码9537完成验证，完成后再次发送请求得到ticket

### ISSUE THREAD

**Issue by 1guankui** [ForteScarlet/simpler-robot#671]
### 版本号

simboot-core-spring-boot-starter：3.0.0；simbot-component-mirai-core：3.0.0.0-RC.2

### 涉及的编程语言

Java

### 涉及的组件库

mirai(QQ)

### 疑问描述

请在手机端使用请求码9537完成验证，完成后再次发送请求得到ticket，这如何操作？
我知道怎么获取ticket，但是使用请求码9537是什么意思？

**Comment by ForteScarlet** [comment]
请求码大概是在 https://github.com/KasukuSakura/mirai-login-solver-sakura 上使用的

**Comment by windy664** [comment]
> 请求码大概是在 https://github.com/KasukuSakura/mirai-login-solver-sakura 上使用的

所以什么意思嗷嗷

**Comment by ForteScarlet** [comment]
> > 请求码大概是在 https://github.com/KasukuSakura/mirai-login-solver-sakura 上使用的
> 
> 所以什么意思嗷嗷

@suiheng 下载链接中的软件并将请求码放到里面来获取 `ticket`
