### ISSUE TITLE
完善QQ频道Core组件的论坛事件的订阅

### ISSUE THREAD

**Issue by Flock-YT** [ForteScarlet/simpler-robot#673]
### 建议描述

如果有时间的话:)

OPEN_FORUMS_EVENT (1 << 18)      // 论坛事件, 此为公域的论坛事件
  - OPEN_FORUM_THREAD_CREATE     // 当用户创建主题时
  - OPEN_FORUM_THREAD_UPDATE     // 当用户更新主题时
  - OPEN_FORUM_THREAD_DELETE     // 当用户删除主题时
  - OPEN_FORUM_POST_CREATE       // 当用户创建帖子时
  - OPEN_FORUM_POST_DELETE       // 当用户删除帖子时
  - OPEN_FORUM_REPLY_CREATE      // 当用户回复评论时
  - OPEN_FORUM_REPLY_DELETE      // 当用户删除评论时

FORUMS_EVENT (1 << 28)  // 论坛事件，仅 *私域* 机器人能够设置此 intents。
  - FORUM_THREAD_CREATE     // 当用户创建主题时
  - FORUM_THREAD_UPDATE     // 当用户更新主题时
  - FORUM_THREAD_DELETE     // 当用户删除主题时
  - FORUM_POST_CREATE       // 当用户创建帖子时
  - FORUM_POST_DELETE       // 当用户删除帖子时
  - FORUM_REPLY_CREATE      // 当用户回复评论时
  - FORUM_REPLY_DELETE      // 当用户删除评论时
  - FORUM_PUBLISH_AUDIT_RESULT      // 当用户发表审核通过时

**Comment by ForteScarlet** [comment]
事件完善之前可以临时使用API模块的 [Unknown](https://docs.simbot.forte.love/components/qq-guild/simbot-component-qq-guild-api/love.forte.simbot.qguild.event/-signal/-dispatch/-unknown/index.html)  事件和组件（core）模块的 [QGUnsupportedEvent](https://docs.simbot.forte.love/components/qq-guild/simbot-component-qq-guild-core-common/love.forte.simbot.component.qguild.event/-q-g-unsupported-event/index.html) 临时处理，缺点是得自己解析一下json

**Comment by Flock-YT** [comment]
在Springboot环境下该怎么使用

**Comment by ForteScarlet** [comment]
监听 [QGUnsupportedEvent](https://docs.simbot.forte.love/components/qq-guild/simbot-component-qq-guild-core-common/love.forte.simbot.component.qguild.event/-q-g-unsupported-event/index.html) 事件，当 `event.sourceEventEntity` 的类型为 [Unknown](https://docs.simbot.forte.love/components/qq-guild/simbot-component-qq-guild-api/love.forte.simbot.qguild.event/-signal/-dispatch/-unknown/index.html) 时进行处理，比如直接解析原始的事件JSON字符串 之类的

```java
@Listener
 public void onEvent(QGUnsupportedEvent event) {
        Signal.Dispatch sourceEvent = event.getSourceEventEntity();
        if (sourceEvent instanceof Signal.Dispatch.Unknown unknown) {
            // 原始事件JSON字符串，解析之类的
            // 也等同于 event.getEventRaw()
            String raw = unknown.getRaw();
            // ...
        }

    }
```

> **Warning**
> 代码仅供参考，未经测试

**Comment by Flock-YT** [comment]
![image](https://github.com/simple-robot/simpler-robot/assets/109157284/012c6356-2129-4a86-a994-871b8d973b52)

QQ的频道机器人的官方文档中要传入一个intents才能订阅到某个事件,在使用Simbot时要如何实现,还是说只能另外自己连接WSS来实现?

**Comment by ForteScarlet** [comment]
SpringBoot 环境下参考 [文档#Bot配置文件](https://simple-robot.github.io/simbot-component-qq-guild/docs/bot-config/#configintents) 中的 `intents`，可以使用 `type: "raw"` 的类型直接指定一个 `instants` 数值

```json5
{
// 其他必要项省略
"config": {
    "intents": {
      "type": "raw",
      "intents": 1073741827 // 实际的 intents
    }
  }
}

```

**Comment by Flock-YT** [comment]
经过测试,已经实现订阅还未支持的事件,以上方法可以走通,感谢指导.
