### ISSUE TITLE
缓存问题，覆盖缓存

### ISSUE THREAD

**Issue by 1guankui** [ForteScarlet/simpler-robot#676]
### 版本号

simboot-core-spring-boot-starter：3.0.0；simbot-component-mirai-core：3.0.0.0-RC.2

### 涉及的编程语言

Java

### 疑问描述

这是springboot框架运行的缓存
![图片](https://github.com/simple-robot/simpler-robot/assets/73282098/91bcf758-7a40-4d77-b38c-c6887766cf5b)

这是【扫码登录】Mirai一键整合包 2.15.0-M1的缓存
![图片](https://github.com/simple-robot/simpler-robot/assets/73282098/a1efd6ed-6980-43f4-abcf-185fa632f510)

相比之下，用springboot写代码运行的缓存只有，validator.bin。
即使替换了后者的缓存，运行后也只剩下validator.bin
请问哪里配置不会覆盖缓存？"loginCacheEnabled": true 或者false都试过了
这是不是我每次运行都要验证码的原因？

**Comment by ForteScarlet** [comment]
参考 https://github.com/simple-robot/simbot-component-mirai README 中 `cache 目录的默认行为` 的说明，默认情况下每个bot都会在 cache 目录下的独立子目录保存信息。
mirai的缓存操作完全由mirai自身控制，这应当与是否使用 SpringBoot 没有太大关系。可能mirai会在一些情况下清理、重置或者删除自己的缓存，或者在某些情况下不生成缓存。这些有可能是内部行为，我也没发现除了 `loginCacheEnabled` 以外的其他类似的可配置项。
