### ISSUE TITLE
关于QQ频道组件核心模块下的QGForumThreadCreateEvent的事件ID

### ISSUE THREAD

**Issue by Flock-YT** [ForteScarlet/simpler-robot#702]
### 版本号

Simbot版本：3.1.0   QQ频道组件版本：3.0.0-alpha.8

### 涉及的编程语言

Java

### 涉及的组件库

QQ频道

### 疑问描述

监听这个事件的时候直接通过
![image](https://github.com/simple-robot/simpler-robot/assets/109157284/bcfdfb35-085b-47d4-982a-bfe5691b3b88)
调出来的事件ID是这样的
![image](https://github.com/simple-robot/simpler-robot/assets/109157284/400a7802-471c-4a83-bcc7-3ea229bad5de)
但是我自己看了一下原始的RAW发现ID是长这样的
![image](https://github.com/simple-robot/simpler-robot/assets/109157284/fba68e7f-3876-4232-adfc-4e7c7e60ea4c)
并且我没在原RAW里找到通过.getID调用出来的那串东西,所以想问一下是不是解析错了,还是说这个ID是自己生成的事件ID.

**Comment by ForteScarlet** [comment]
[主题事件](https://bot.q.qq.com/wiki/develop/api/gateway/forum.html#主题事件) 中并没有明确提及存在一个 `id` 属性，因此印象中我并没有解析这个 `id` ，所以得到的 id 实际上是一个普通的随机id

**Comment by Flock-YT** [comment]
哪是否可以在后面的更新中解析一下这个ID,或者直接把那个普通的ID替换成这个,因为RAW里的那个ID里面包含很重要的信息.

**Comment by ForteScarlet** [comment]
我并不倾向于为一个他们文档中未提及的属性提供解析，毕竟如果未来发生变更或属性消失会比较麻烦。

这个属性有哪些重要信息以及是否有频道官方的人明确此字段的存在性？

_一个比较简单的办法是直接自行解析 raw 截取一下就好_

**Comment by Flock-YT** [comment]
好的十分感谢
