### ISSUE TITLE
QQ频道-无法发送图片

### ISSUE THREAD

**Issue by way-zer** [ForteScarlet/simpler-robot#703]
### 版本号

v3.1.0

### 附加版本

love.forte.simbot:simbot-core:3.1.0
love.forte.simbot.component:simbot-component-qq-guild-core:3.0.0.0-alpha.8

### 涉及的编程语言

Kotlin

### 项目构建工具

其他

### 涉及的组件库

QQ频道

### 问题描述

发送图片失败
![image](https://github.com/simple-robot/simpler-robot/assets/15688938/88059e23-8082-4ca5-b775-c6c931a7e07c)

### 复现方式

```kotlin
ChannelMessageEvent{
            val image = File("/mnt/develop/0.png").toResource().toImage()
            it.replyIfSupport(image)
}
```
复现用图片:
https://p.qpic.cn/qqconadmin/0/b095d8d0ad144de3943f5dcba95a9624/0

**Comment by way-zer** [comment]
alpha9发送图片正常，但图文混合仍然有问题
文字部分被异常编码(额外的引号，以及换行符失效)
![image](https://github.com/simple-robot/simpler-robot/assets/15688938/233be130-a5e2-42c8-9be4-bf58696ebb36)
```kotlin
message.replyIfSupport(Text { text })
message.replyIfSupport(Text { text } + image)
```

**Comment by ForteScarlet** [comment]
- 当 https://github.com/simple-robot/simbot-component-qq-guild/pull/92 合并后会推送一个新的 `v3.1.0.0-alpha.9-SNAPSHOT` ，届时请尝试刷新快照并尝试其效果

**Comment by ForliyScarlet** [comment]
此issue已经在「等待反馈」状态下5日未应答。如果在「陈旧」状态下逾期2日将会被视为无效过期并关闭。
