### ISSUE TITLE
程序主动向特定频道发送消息，应该怎么处理合适

### ISSUE THREAD

**Issue by axiangcoding** [ForteScarlet/simpler-robot#704]
### 版本号

v3.1.0

### 涉及的编程语言

Java

### 涉及的组件库

KOOK

### 疑问描述

文档中提到的事件触发模型十分符合我的心意，但是这种定义中，事件是由平台触发的，比如说收到了一条频道消息，那么可以这样写
```
@Component
@Slf4j
public class MyListener {
    @Listener
    public void onEvent(ChannelMessageEvent event) {
        log.info("监听到了 {}", event.getMessageContent().getPlainText());
        event.replyAsync("你好，我是机器人");
    }
}
```
假设事件是由我的程序触发的，那我应该怎么写？比如我的程序会做一些定时的任务，触发了向某个频道或者某个用户发送消息的任务，我能否构建一个类似 的Event来使用listener的方式发送消息？

我不是很想在代码中再调用api发送请求，这看起来不够优雅

比如先在触发的位置注册一个event：
```
CustomEvent event = CustomeEvent.builder().build();
// 设置必要的channelid, messageid, guildid等内容
event.registerToSimbot();
```

然后再监听event:
```
@Component
@Slf4j
public class MyListener {
    @Listener
    public void onEvent(CustomeEvent event) {
        log.info("监听到了 {}", event.getMessageContent().getPlainText());
        event.replyAsync("你好，我是机器人");
    }
}
```

**Comment by ForteScarlet** [comment]
参考 [Discussions#74](https://github.com/orgs/simple-robot/discussions/74) ，道理类似，将其中 `MiraiXxx` 视为 `KookXxx` 即可

以及在 KOOK 中没有 `Group` ，可将其视为 `Channel`

**Comment by axiangcoding** [comment]
> 参考 [Discussions#74](https://github.com/orgs/simple-robot/discussions/74) ，道理类似，将其中 `MiraiXxx` 视为 `KookXxx` 即可
> 
> 以及在 KOOK 中没有 `Group` ，可将其视为 `Channel`

ok感谢，这个可以解决我的疑惑
