### ISSUE TITLE
[BUG] 猫猫码参数转义缺失等号转义

### ISSUE THREAD

**Issue by niehaiyang** [ForteScarlet/simpler-robot#71]
version: `2.0.0-BETA.5` 

module: `` 

## 问题描述

GroupMsg.getMsg()无法获取到以“=”号结尾的msg

## 复现方式

群内发送以“=”结尾的消息，控制台输出GroupMsg.getMsg()，值为空

**Comment by ForteScarlet** [comment]
[catcode #3](https://github.com/ForteScarlet/CatCode/issues/3)

**Comment by ForteScarlet** [comment]
fix by [catcode v1.0.0-BETA.1](https://github.com/ForteScarlet/CatCode/releases/tag/v1.0.0-BETA.1)

**Comment by ForteScarlet** [comment]
临时解决方案：

<properties>
    <catCode.version>1.0.0-BETA.1</catCode.version>
</properties>

<dependency>
    <groupId>love.forte</groupId>
    <artifactId>catcode</artifactId>
    <version>${catCode.version}</version>
</dependency>
