### ISSUE TITLE
KOOK怎么发送临时消息

### ISSUE THREAD

**Issue by axiangcoding** [ForteScarlet/simpler-robot#718]
### 版本号

v3.1.0

### 涉及的编程语言

Java

### 涉及的组件库

KOOK

### 疑问描述

KOOK怎么发送临时消息，即https://developer.kookapp.cn/doc/http/message#%E5%8F%91%E9%80%81%E9%A2%91%E9%81%93%E8%81%8A%E5%A4%A9%E6%B6%88%E6%81%AF 中的描述

**Comment by ForteScarlet** [comment]
直接使用原始 [API](https://docs.simbot.forte.love/components/kook/simbot-component-kook-api/love.forte.simbot.kook.api.message/-message-create-request/-key/index.html) 可以指定 `temp_target_id` ，不过 `core` 模块中似乎是忘记提供对应的能力了。

**Comment by axiangcoding** [comment]
考虑到编写代码的一致性，是否可以考虑支持，譬如
```
event.sendBlocking(Message(), Config(temp=true))
```
单独使用API虽然可以，但是感觉不够优雅

**Comment by ForteScarlet** [comment]
按照风格，我们会考虑在 `core` 模块中提供一个例如 `KookTempTarget` 的消息元素类型，就像 [KookAtAllHere](https://docs.simbot.forte.love/components/kook/simbot-component-kook-core/love.forte.simbot.component.kook.message/-kook-at-all-here/index.html) 或 QQ频道中的 [QGReplyTo](https://docs.simbot.forte.love/components/qq-guild/simbot-component-qq-guild-core-common/love.forte.simbot.component.qguild.message/-q-g-reply-to/index.html)

> 单独使用API虽然可以

诸如此类的消息相关能力非必要不会产生独立的API函数。

**Comment by axiangcoding** [comment]
好的，期待相关的实现
