### ISSUE TITLE
kook组件库高低版本识别错误

### ISSUE THREAD

**Issue by axiangcoding** [ForteScarlet/simpler-robot#720]
### 版本号

v3

### 涉及的编程语言

Java

### 项目构建工具

Gradle

### 涉及的组件库

KOOK

### 问题描述

maven仓库中，不知道为什么错误识别了较老的版本为最新的版本，即将 
`simbot-component-kook-core:3.0.0.0.preview.14.0`视为高于 `simbot-component-kook-core:3.0.0.0-alpha.6` 的版本，见 https://mvnrepository.com/artifact/love.forte.simbot.component/simbot-component-kook-core/3.0.0.0-alpha.6

导致github dependabot自动更新会更新到低版本

### 复现方式

见 https://github.com/axbot-dev/axbot/pull/173

### 其他补充

建议调整该规则，避免dependabot的错误更新

**Comment by ForteScarlet** [comment]
https://issues.sonatype.org/browse/MVNCENTRAL-8031

这是早期版本命名不规范导致的。直到更新到下一个阶段版本（比如 `v3.1.0.0-xxx` 或 `v3.0.0.1-xxx` 之外没有解决办法
