### ISSUE TITLE
关于语音的发送

### ISSUE THREAD

**Issue by SmallWhitedawsd** [ForteScarlet/simpler-robot#721]
### 版本号

3.0.0.0-RC.2

### 涉及的编程语言

Java

### 疑问描述

图片啥的都有参考文档，语音的呢，语音有吗？ 语音怎么发送

**Comment by ForteScarlet** [comment]
是否有语音取决于组件的实现，它并不在标准API中定义。
例如 mirai 有 [MiraiAudio](https://docs.simbot.forte.love/components/mirai/simbot-component-mirai-core/love.forte.simbot.component.mirai.message/-mirai-audio/index.html) 类型实现（#400），而KOOK或QQ频道组件则没有直接发送语音的能力。

**Comment by JacianZhu** [comment]
@SmallWhitedawsd  你这登录是通过什么方式 ，我现在登录都不行 扫码的？

**Comment by ForliyScarlet** [comment]
此issue已经在「等待反馈」状态下5日未应答。如果在「陈旧」状态下逾期2日将会被视为无效过期并关闭。

**Comment by ForliyScarlet** [comment]
此issue已经在「陈旧」状态下逾期2日未应答, 视为无效过期并关闭。
