### ISSUE TITLE
QQ频道怎么发送私信

### ISSUE THREAD

**Issue by axiangcoding** [ForteScarlet/simpler-robot#727]
### 版本号

v3.2.0

### 涉及的编程语言

Java

### 涉及的组件库

QQ频道

### 疑问描述

QQ频道怎么发送私信，能拿到event对象

**Comment by ForteScarlet** [comment]
- 可尝试通过 `bot.getContract(...)` 获取一个联系人对象，并通过其发送消息。得到的 `Contact`  对象实际类型应当是 [KookContact](https://docs.simbot.forte.love/components/kook/simbot-component-kook-core/love.forte.simbot.component.kook/-kook-contact/index.html) 

-  在频道中也可以通过获取 `member` 并使用 `send` 发送私聊消息，得到的 `member` 实际类型应当是 [KookGuildMember](https://docs.simbot.forte.love/components/kook/simbot-component-kook-core/love.forte.simbot.component.kook/-kook-guild-member/index.html)

- 私聊相关的事件有实现了 [ContactMessageEvent](https://docs.simbot.forte.love/main/simbot-api/love.forte.simbot.event/-contact-message-event/index.html)  的  [KookContactMessageEvent](https://docs.simbot.forte.love/components/kook/simbot-component-kook-core/love.forte.simbot.component.kook.event/-kook-contact-message-event/index.html) ，直接使用其 `reply` 应当也可以达到回复私聊的效果。

> 如果上述方式中有预期外的结果则大概是BUG，可通过 Issues 反馈。

**Comment by axiangcoding** [comment]
> * 可尝试通过 `bot.getContract(...)` 获取一个联系人对象，并通过其发送消息。得到的 `Contact`  对象实际类型应当是 [KookContact](https://docs.simbot.forte.love/components/kook/simbot-component-kook-core/love.forte.simbot.component.kook/-kook-contact/index.html)
> * 在频道中也可以通过获取 `member` 并使用 `send` 发送私聊消息，得到的 `member` 实际类型应当是 [KookGuildMember](https://docs.simbot.forte.love/components/kook/simbot-component-kook-core/love.forte.simbot.component.kook/-kook-guild-member/index.html)
> * 私聊相关的事件有实现了 [ContactMessageEvent](https://docs.simbot.forte.love/main/simbot-api/love.forte.simbot.event/-contact-message-event/index.html)  的  [KookContactMessageEvent](https://docs.simbot.forte.love/components/kook/simbot-component-kook-core/love.forte.simbot.component.kook.event/-kook-contact-message-event/index.html) ，直接使用其 `reply` 应当也可以达到回复私聊的效果。
> 
> > 如果上述方式中有预期外的结果则大概是BUG，可通过 Issues 反馈。

这里是qq频道，应该不是`KookContact`吧。

不过我已经尝试过这种方式，当 bot.getContact(id) 的时候，使用了正确的id但是返回的Contact是null，暂不清楚为什么

**Comment by ForteScarlet** [comment]
哦哦看错了，QQ频道的话 `Contact` 是没有的，因为 [创建私信会话](https://bot.q.qq.com/wiki/develop/api/openapi/dms/post_dms.html#%E6%8E%A5%E5%8F%A3) 始终与频道相关。因此私聊应该通过 `member` 进行

**Comment by ForteScarlet** [comment]
对于事件的话，私聊消息事件core模块下暂未支持，可追踪 https://github.com/simple-robot/simbot-component-qq-guild/issues/103 ，可以临时使用 [QGUnsupportedEvent](https://docs.simbot.forte.love/components/qq-guild/simbot-component-qq-guild-core-common/love.forte.simbot.component.qguild.event/-q-g-unsupported-event/index.html) 配合 API 模块中的 [DirectMessageCreate](https://docs.simbot.forte.love/components/qq-guild/simbot-component-qq-guild-api/love.forte.simbot.qguild.event/-direct-message-create/index.html) 达到监听事件的目的

**Comment by axiangcoding** [comment]
> 对于事件的话，私聊消息事件core模块下暂未支持，可追踪 [simple-robot/simbot-component-qq-guild#103](https://github.com/simple-robot/simbot-component-qq-guild/issues/103) ，可以临时使用 [QGUnsupportedEvent](https://docs.simbot.forte.love/components/qq-guild/simbot-component-qq-guild-core-common/love.forte.simbot.component.qguild.event/-q-g-unsupported-event/index.html) 配合 API 模块中的 [DirectMessageCreate](https://docs.simbot.forte.love/components/qq-guild/simbot-component-qq-guild-api/love.forte.simbot.qguild.event/-direct-message-create/index.html) 达到监听事件的目的

好的，不过暂不需要监听私聊事件

**Comment by ForliyScarlet** [comment]
此issue已经在「等待反馈」状态下5日未应答。如果在「陈旧」状态下逾期2日将会被视为无效过期并关闭。
