### ISSUE TITLE
在idea中可以正常运行，打包后使用java -jar启动提示Bot verify info [xxx] registration failed or start failed错误

### ISSUE THREAD

**Issue by keithfeng425** [ForteScarlet/simpler-robot#735]
### 版本号

v3.2.0

### 涉及的编程语言

Java

### 项目构建工具

Maven

### 涉及的组件库

mirai (QQ)

### 问题描述

在idea中运行毫无问题：
![image](https://github.com/simple-robot/simpler-robot/assets/36266938/a772bede-9a46-42e4-9d38-be5de3eb8e3f)

通过maven进行package后，独立运行jar包出现如下报错：
![image](https://github.com/simple-robot/simpler-robot/assets/36266938/3e27c3f3-43da-4735-986d-0e672e233571)
![image](https://github.com/simple-robot/simpler-robot/assets/36266938/f2e96f0a-5138-4403-8311-2156c2041783)

请问这是什么原因导致的呢？

### 复现方式

导入的jar包为fix-protocol-version-1.10.0.mirai2.jar，使用签名服务器为unidbg-fetch-qsign-1.1.7，使用maven打包后，通过java -jar的方式运行

**Comment by ForteScarlet** [comment]
最后一张图最下面信息已经提示：Bot已经被注册过了。检查是否存在重复的bot信息被注册等情况

**Comment by keithfeng425** [comment]
可以请问一下什么样的情况下会出现重复注册的情况吗？因为在Idea里直接运行是没有问题的

**Comment by ForteScarlet** [comment]
> 可以请问一下什么样的情况下会出现重复注册的情况吗？因为在Idea里直接运行是没有问题的

比如resources中存在两个账号相同的配置文件、或者即加载了配置文件，又在代码中手动注册账号等等。

**Comment by keithfeng425** [comment]
好的，我定位到问题所在了，十分感谢您的解答
