### ISSUE TITLE
对其他框架的支持

### ISSUE THREAD

**Issue by noear** [ForteScarlet/simpler-robot#737]
### 建议描述

听人说只能用 spring 全家桶开发。希望也能增加 solon 框架的支持：）

**Comment by ForteScarlet** [comment]
首先是simbot并不是 **_只能用 spring 全家桶开发_** ，只是提供了基于 `simbot-core` 的 `Spring Boot Starter` 以便快速开发（因为实现了注解的解析能力，对 Java 更加友好，如果使用 Kotlin 或不打算使用注解开发，完全可以不使用 Spring Starter ）。

`simbot-core` 模块（或其他相关衍生模块、组件等）都是可独立使用的，并不依附于某特定的框架生态。

我对 solon 并不了解，如果有兴趣或有经历的话完全可以基于 simbot 的基础模块自行实现针对 solon （或者其他框架）的支持。
如果是因为 simbot 基础模块的原因而导致难以或无法对某个框架提供支持，则可以提出 issues 寻求帮助或提供改进建议。

如果实现了对其他框架的支持并且开源，也欢迎在此issue、 [讨论区](https://github.com/orgs/simple-robot/discussions) 等地方留言来分享~😊

**Comment by ForliyScarlet** [comment]
此issue已经在「等待反馈」状态下5日未应答。如果在「陈旧」状态下逾期2日将会被视为无效过期并关闭。
