### ISSUE TITLE
无法登录或者版本过低  code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=

### ISSUE THREAD

**Issue by ghost** [ForteScarlet/simpler-robot#749]
### 建议描述

可以搞一个扫码登录有一个Hbot的github项目就是扫描登录作者你可以参考一下:[https://github.com/happysnaker/hbot](url)

**Comment by ForteScarlet** [comment]
感谢你的建议！
不过对于mirai组件的手表协议、扫码登录的方式，mirai组件是支持的，可参考：
- [mirai组件手册-配置文件-`qr_code`](https://component-mirai.simbot.forte.love/docs/bot-config#qr_code)
- https://github.com/simple-robot/simbot-component-mirai/pull/136

_如有疑问可随时重新开启此issues或继续追加评论_
