### ISSUE TITLE
2.0.2版本无法动态获取参数

### ISSUE THREAD

**Issue by Leibuyun** [ForteScarlet/simpler-robot#76]
@OnGroup
    @Filter(value = "number is {{pageNum,\\d+}}", matchType = MatchType.REGEX_MATCHES, atBot = true, trim = true)
    public void test1(GroupMsg msg, MsgSender sender, @FilterValue("pageNum")  String pageNum) {
        sender.SENDER.sendGroupMsg(msg, msg.getMsgContent() + "---" + pageNum);
    }
无法获取参数

**Comment by ForteScarlet** [comment]
原因：
FilterValue进行匹配的时候没有正确被 `trim=true`，因此还是存在前后空格

临时解决方案：
正则前后追加 ` *`，即“可存在任意空格”，例如：
```
@filter(value = " *number is {{pageNum,\d+}} *", matchType = MatchType.REGEX_MATCHES, atBot = true, trim = true)
```
