### ISSUE TITLE
大佬准备支持KOOK的推流嘛

### ISSUE THREAD

**Issue by wutitaxue** [ForteScarlet/simpler-robot#790]
### 版本号

v4

### 涉及的编程语言

Java

### 涉及的组件库

KOOK

### 疑问描述

大佬准备支持KOOK的推流嘛

**Comment by ForteScarlet** [comment]
推流是什么，有无官方API

**Comment by wutitaxue** [comment]
大概就是用websocket推音视频流
这有个TypeScript的项目，我看不懂
https://github.com/saltcute/koice.js/tree/main

**Comment by ForteScarlet** [comment]
看样子这并不是官方的API，相反
> Before using this package, you confirm you understand by using this package, you are violating
> - Section 3.2.3 or 3.2.5 of the [KOOK Software Permission and Service Agreement](https://www.kookapp.cn/protocol.html), and
> - Section Data Information, or Abusive Use, of the [KOOK Developer Privacy Policy](https://developer.kookapp.cn/doc/privacy)

正如它的 README 所说，这可能会违反 KOOK 的用户协议和隐私政策，并且有面临处罚的风险。
KOOK组件暂不考虑参考或实现这类非官方API提供的功能。
