### ISSUE TITLE
QQ消息里面的图片无法重复读取

### ISSUE THREAD

**Issue by xorange1997** [ForteScarlet/simpler-robot#822]
### 版本号

v4.0

### 涉及的编程语言

Java

### 涉及的组件库

其他

### 疑问描述

你好，就是QQ的图片消息不能重复读取，有人发了一条消息给机器人之后未处理成功，之后我转发想重新处理一次，但是发现图片不能获取到了？
<img width="1445" alt="image" src="https://github.com/simple-robot/simpler-robot/assets/38392442/413e27ed-087c-4469-b748-a38380c68030">

**Comment by ForteScarlet** [comment]
这是通过 `URL.openStream` 产生的异常，但是这似乎是 V3 的内容，错误的原因与定位会比较麻烦。
比较快速的解决方案是通过判断 `resource` 是否为 `URLResource` 来获取 `URL` 并自行处理此链接。

```Java
if (resource instanceof URLResource urlResource) {
    URL url = urlResource.getUrl();
    // 直接处理这个 URL 
}
```

**Comment by xorange1997** [comment]
好的 谢谢
