### ISSUE TITLE
监听QGGroupAtMessageCreateEvent事件能获取到发言人的群聊昵称吗

### ISSUE THREAD

**Issue by ParNal3355** [ForteScarlet/simpler-robot#931]
### 版本号

4.6.0

### 涉及的编程语言

Java

### 涉及的组件库

QQ机器人

### 疑问描述

监听QGGroupAtMessageCreateEvent事件能获取到发言人的群聊昵称吗，找了一下午了，获取群聊id用户id的方法都找到了这个实在是找不到了QAQ

**Comment by ForteScarlet** [comment]
参考[官方文档](https://bot.q.qq.com/wiki/develop/api-v2/server-inter/message/send-receive/event.html#%E7%BE%A4%E8%81%8A-%E6%9C%BA%E5%99%A8%E4%BA%BA)，只能获取到发送人的某种 `open_id`，无法获取到昵称和QQ号，官方也未提供用于获取这些信息的 API。
简单来说，获取不到。

**Comment by ForteScarlet** [comment]
未来会不会有不知道，但是现阶段确实没有，至少我也没找到。
